### ISSUE TITLE
Action Bar

### ISSUE THREAD

**Issue by danielromlein** [kubernetes/dashboard#1015]
#### About

Dashboard should incorporate a way for users to take actions on the various components they're managing. [UX and navigation that scales](https://github.com/kubernetes/dashboard/blob/master/docs/design/navigation-and-scale.md#design) proposes "introduction of action bar for performing all actions on resources." 
#### Goal

Decide what actions a user needs to be able to take, on which objects, so that we can start exploring UX patterns that best serve those objectives. 

I could see as an effective approach for this a spreadsheet with its two axes representing components and potential actions.

**Comment by bryk** [comment]
Current state is:
* on pages that list things, in action bar you can "deploy an app" and "upload YAML"
* on pages that show a thing you can "delete" and "edit" the thing

To me, the desired state is:
* on pages that list things:
  *  you have a button "create a thing" that allows you to upload/paste YAML or fill a form
  * you can multi-select things and click "delete"
  * (distant future) you can multi-select and click "edit"
* on pages that show a thing:
  * you delete the thing
  * you can YAML-edit the thing
  * (future) you can edit the thing via custom form
  * you can do custom verb actions applicable to the resource (e.g., do a rolling update or expose the service). Every resource has 0-2 custom actions. In extreme cases this may be 3.

**Comment by romlein** [comment]
@bryk would it make sense to distinguish between global and local _actions_ and move 'Deploy App' and 'Upload YAML' to the top bar while keeping local objects in the page that they're affecting? See: [this sketch](https://invis.io/XZ7RITOQD#/174711855_IMG_9443). Can a user 'Deploy App' or 'Upload YAML' from anywhere within Dashboard?

I still don't have a great understanding between 'Deploy App' and 'Upload YAML' – would you mind explaining again why we want to have both those present? To me it seems like a subtle distinction that maybe would be better left to selection of an option once a user has clicked _one_ main call-to-action.

**Comment by bryk** [comment]
> @bryk would it make sense to distinguish between global and local actions and move 'Deploy App' and 'Upload YAML' to the top bar while keeping local objects in the page that they're affecting? See: this sketch. Can a user 'Deploy App' or 'Upload YAML' from anywhere within Dashboard?

Yeah, this makes total sense. I strongly support this idea. The reason we have those items there is the fact that this is the only way we _currently_ can create things. It is like a stop gap solution. In ideal world we would have "Create a workload" button on workloads page and "create a secret" button on secrets list. Since we're not there yet, we decided to add app deploy + YAML upload buttons everywhere, since you can create everything through YAML upload. This has just not been done yet, but next quarter+ is a realistic timeframe. 

> I still don't have a great understanding between 'Deploy App' and 'Upload YAML' – would you mind explaining again why we want to have both those present? To me it seems like a subtle distinction that maybe would be better left to selection of an option once a user has clicked one main call-to-action.

We wanted to expose the option of YAML upload because it is a gateway to _everything_. App creation form is nice for beginners, but once you use the system, you need something more powerful. But there is nothing that prevents us from merging this back into one, as long as it is discoverable that we have the powerful YAML upload.

**Comment by bryk** [comment]
> See: this sketch. 

Maybe off-topic, but I see breadcrumbs there. Remember that once we have left-nav, the breadcrumbs are probably obsolete and can be removed.

**Comment by romlein** [comment]
@bryk that explanation makes sense – thanks! Now we have that recorded someplace where I can find it again 😊
Noted on the breadcrumb.

**Comment by romlein** [comment]
I updated the [Dashboard nav mockup](https://invis.io/XZ7RITOQD#/172317298_Full_Width) to include the action bar – split between local and global actions.

**Comment by Lukenickerson** [comment]
@romlein - I think the latest draft looks really nice:

![image](https://cloud.githubusercontent.com/assets/3942453/16954694/c86ef7a6-4d9f-11e6-8f10-b7d01aac6031.png)


I think the "Upload YAML" button could be removed because it doesn't tell the user _what_ the action is doing (which might not be obvious for a beginner), and is redundant with the "Deploy App" button. IMO better to only have one action button for **_what_** the user is trying to accomplish (i.e., "Deploy an app onto the cluster"), then allow them to easily select **_how_** to do the action (either specifying information or uploading a YAML). My assumption is that a developer will typically use either one method or the other, not both, so ideally we would remember that selection for the future (localStorage perhaps) to make it even easier for them.

**Comment by romlein** [comment]
@Lukenickerson those are great points about focusing on the _what_ a user wants to accomplish.

@bryk's [comment](https://github.com/kubernetes/dashboard/issues/1015#issuecomment-233335049)
>you can create everything through YAML upload

Makes me wonder if we need to have a single more generic "Create" option; would that make sense? "Create" and then pick the _what_ (e.g. a workload, a secret)?

**Comment by floreks** [comment]
> Makes me wonder if we need to have a single more generic "Create" option; would that make sense? "Create" and then pick the what (e.g. a workload, a secret)?

Good point. I like this idea. From any view in dashboard we could create any resource.

**Comment by bryk** [comment]
> Makes me wonder if we need to have a single more generic "Create" option; would that make sense? "Create" and then pick the what (e.g. a workload, a secret)?

Yes, that's a good idea. One button which then let's you decide whether you want to create an app or upload YAML to create _anything_. This can be either a "Dropdown button" from [material spec](https://material.google.com/components/buttons.html#buttons-persistent-footer-buttons) or normal button than later let's you decide what to do.

**Comment by romlein** [comment]
I like the idea of a dropdown button. We can explore what the best pattern there is.

**Comment by romlein** [comment]
Something to consider for the per-menu-item action items is an approach like Google Keep takes, where a user selects the object(s) they'd like to affect, then the top header is replaced by relevant options.
![google-keep-action-pattern](https://cloud.githubusercontent.com/assets/5114858/16987322/9a77a2d4-4e59-11e6-899b-4012e09847a8.jpg)

**Comment by maciaszczykm** [comment]
>Something to consider for the per-menu-item action items is an approach like Google Keep takes, where a user selects the object(s) they'd like to affect, then the top header is replaced by relevant options.

@romlein Yes, it's very good idea. It'd cover #1016 issue.

**Comment by romlein** [comment]
@bryk if we don't use a UX pattern like the Keep-esque one screenshotted above, @Lukenickerson brought up the point that we'd want to decide what to do when content extends down the page and a user scrolls down: would the action bar need to be sticky somehow so a user could access from any point of content?

**Comment by cheld** [comment]
@romlein Inbox also has similar header behavior.

**Comment by bryk** [comment]
> would the action bar need to be sticky somehow so a user could access it from any point of content?

Yes, I'd say so. I exect that we'll have long-ish pages, which require users to scroll them down. You could then see a thing and would like to take action on them. The thing to consider is to make the actionbar hide on scroll down. This is how most of your mobile apps work. They have an actionbar/toolbar which hides when scrolling down.

**Comment by romlein** [comment]
@bryk hiding the action bar on scroll seems like a good option. Whether or not that's the best solution depends on how available we want to have the actions.

**Comment by romlein** [comment]
I have two concerns around the Inbox / Keep functionality of swapping out the header:
 1. A user has to select one or more table rows in order to bring up actions. If there are actions they would want to be able to take _independent_ of having selected objects this wouldn't work. 
 2. Having the actions appear at the top gives them the prominence of global-level objects, when in fact they are subordinate to controls like Namespace. 

Thoughts?

**Comment by bryk** [comment]
@romlein I agree with the concerns. That's why I like top-bar for global stuff and action bar for page-local actions.

**Comment by Lukenickerson** [comment]
I started putting together a list of all the navigation areas, resources (objects) we're working with, and what actions are possible on each resource -- both on the list view or the individual view. https://docs.google.com/spreadsheets/d/1GnnZ8gUUA4jLcUH1WoCb8MsPQNeCKGcNjnDr-DwcYoU/edit#gid=507136643 Please add comments or request to edit. I think it would be helpful to get all the unknowns ("?") filled in.

**Comment by bryk** [comment]
@Lukenickerson Nice setup of the spreadsheet! Do you look for feedback/help on the contents of it? Or is it still WIP?

**Comment by Lukenickerson** [comment]
@bryk -- I'm hoping for feedback. Please make edits or leave comments.

**Comment by bryk** [comment]
Awesome. Added a few comments there. PTAL

**Comment by romlein** [comment]
@Lukenickerson just requested "Edit" access – I was just going to copy in the suggestions from @bryk's comments. @bryk if you get a chance to request "Edit" access and do that directly that might be more streamlined.

**Comment by bryk** [comment]
Just requested edit access.

**Comment by maciaszczykm** [comment]
Closing as stale. At the moment we are using two action bars. Global where you can find auth panel and create action (which is not finished yet - it requires a lot of work and is a low priority now). Local which has view-specific actions like exec, logs, edit and delete for the pod in an example.
