### ISSUE TITLE
'gulp check' hangs when tests fail

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#111]
'gulp check' hangs when tests fail. This causes travis to execute the task for 50 minutes to return the error. Example: https://travis-ci.org/kubernetes/dashboard/builds/94143810

**Comment by zreigz** [comment]
I can take this

**Comment by bryk** [comment]
The issue actually happens not only when tests fail. Also when there is any other failure, e.g, lint or script compilation. The issue, I think, is that gulp swill waits for cluster to come up.

**Comment by zreigz** [comment]
I will try find some global solution for error handling in gulp

**Comment by bryk** [comment]
How about making local-up-cluster task finish only when the cluster is up, running and healthy? This will allow to remove wait-for-cluster task and, in result, remove the deadlock. Am I correct?

**Comment by zreigz** [comment]
Right now we doing like this. The wait-for-cluster task finish local-up-cluster when the cluster is up, running and healthy and then backend server can be started. Every error before spawn-cluster will cause the problem described in this issue because wait-for-cluster waits for task which never started and was interrupted by error (so it won't be started)

My approach is to create gulp task which handle all errors in gulp process. Every error should finish entire gulp process: prcess.exit(exitCode). We prevent deadlocks and decouple code from additional checks in tests, lint or script compilation. Before local-up-cluster we had simple task chain and in the case of error gulp process was interrupted and exit with some code. Now we have to create such mechanism because of complexity of local cluster.

**Comment by cheld** [comment]
Currently, 

the cluster-creation and the integration-tests are started in parallel (asynchronously). Therefore, the integration-tests must wait until cluster is ready. I have not tested, but I assume to make the local-up-cluster wait until it is ready is useless, because the gulp task will not finish before the cluster is running anyway.

IMHO we have two options:
1. Try to understand error handling and dependencies in parallel executions more deeply. 
2. Create cluster synchronously. This will make the CI a bit slower. In development case we suggest to create a separate console tab anyway. So, experience will not change.

**Comment by zreigz** [comment]
Now I've been trying first solution because waiting for cluster can take 5-7min when is created from scratch. If I find something I will share with you.

**Comment by bryk** [comment]
I agree with @cheld. Try making the loca-up-cluster task synchronous and finish it only when the cluster is healthy. This would most likely require moving it to dependency of integration tests. And I think this would not affect CI execution time, as integration tests are waiting for the cluster and all tasks execute in parallel anyway.

**Comment by zreigz** [comment]
I was searching how to create error handler for asynchronous tasks. I found out the run-sequence plugin has this functionality. It could be like this:
```
import sequence from 'run-sequence';

gulp.task('check', function () {
  runSequence(['lint', 'build', 'test', 'integration-test:prod'],
    // it will be used as a callback after all the tasks are either finished or an error has occurred.
    function (err) {
      gulp.start('kill-all'); //or other clean up staff 
      if(err) {
        process.exit(1);
      }
  });
});
```
Maybe it will be helpful for the future.

**Comment by bryk** [comment]
This is done, isn't it?
