### ISSUE TITLE
v1.4.0 amd image is stale

### ISSUE THREAD

**Issue by mindw** [kubernetes/dashboard#1261]
#### Issue details
`gcr.io/google_containers/kubernetes-dashboard-amd64:v1.4.0` is dated 5 days ago:
```
$ docker history gcr.io/google_containers/kubernetes-dashboard-amd64:v1.4.0
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
7f958a44b6fc        5 days ago          /bin/sh -c #(nop) ENTRYPOINT &{["/dashboard"    0 B
<missing>           5 days ago          /bin/sh -c #(nop) EXPOSE 9090/tcp               0 B
<missing>           5 days ago          /bin/sh -c #(nop) ADD dir:14ee553d707af1c8e88   86.27 MB
<missing>           6 months ago        /bin/sh -c #(nop) MAINTAINER Piotr Bryk <bryk   0 B
```

##### Environment

```
Dashboard version: v1.4.0
Kubernetes version: v1.3.6
Operating system: 
Node.js version:
Go version:
```

##### Steps to reproduce

Use the above image on any k8s setup (minikube, cloud vendor etc)
- set `imagePullPolicy: Always` to avoid stale images
- `kubectl proxy`
- open `http://localhost/8001/ui`

##### Observed result

CPU metrics still go below 0 & the log view is from pre refactoring.

##### Expected result

The above issues gixed

**Comment by bryk** [comment]
This will be updated later today or tomorrow. Thanks for reporting :) 

The longer story behind this is as follows. We synchronize major releases with Kubernetes core 1.4. But in order this to happen we need to send a PR to the core repo with updated image like a week before the actual release (due to code freeze there). So we build the image, push it and after a week we actually publish release here and update the image. I hope this will change for future releases, but that's what we have now.

**Comment by mindw** [comment]
Thanks for the quick reply and explanation!
Its likely you get some dups on this one till the image is posted ...

**Comment by bryk** [comment]
Yes, we're aware of this, but that was the plan for 1.4 release. I'm not super happy with it, so I guess for future we'll just shift our release cycle by, like, two weeks.

**Comment by bryk** [comment]
I just updated the image. PTAL and close if resolved.

**Comment by mindw** [comment]
All is well now!

Thanks keep the great work :)
