### ISSUE TITLE
Introduce auto-refresh mechanism

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/dashboard#1296]
Moving from https://github.com/kubernetes/kubernetes/issues/33755

Using Kubernetes 1.4, `master-ip/ui` shows the dashboard nicely. 

For example, https://52.41.10.66/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard/#/replicationcontroller?namespace=default shows all the Replication Controllers.

New RCs were created and the page had to be manually refreshed to show the newly created RCs.

An auto-refresh capability in the UI would be great.

**Comment by cheld** [comment]
Also, deleted items would disappear :)

**Comment by bryk** [comment]
We had initial thinking on this topic, but when you dig deeper, some issues arise. For example, what if your system is highly dynamic and pods come and go every second? This would cause complete mess.


Would a button like "there are new RCs, refresh" or "turn on autorefresh" help?

**Comment by cheld** [comment]
@batikanu told me there should be an auto-refresh after every own action. Maybe it is missing at some places... Of course, still missing is refresh after own CLI-actions, actions from other users and refresh of graphs.

Some monitoring dashboards offer a auto-refresh button that reloads the model every couple second or so. @bryk could give an example of the problems that it would cause?

**Comment by bryk** [comment]
> @batikanu told me there should be an auto-refresh after every own action

Yes, that's true. But this is only a single refresh.

>@bryk could give an example of the problems that it would cause?

E.g., you're doing a rolling update and your pods appear and disappear from the pod list every second. You want to click a pod, but it disappears from under your pointer (this may be actually the feature users look for, actually).

**Comment by quinnj** [comment]
I also think auto-refresh would be super useful. There could perhaps be some kind of setting to limit how often it was able to refresh (in cases where pods are coming/going sub-second).

**Comment by guenhter** [comment]
Kibana has a nice approach doing the auto-update. 
![GitHub Logo](https://www.elastic.co/guide/en/kibana/6.0/images/autorefresh-intervals.png)

**Comment by andrewrk** [comment]
Auto-refresh is a hack. What we actually want is #2541 - live updates pushed to the browser when the information changes.

**Comment by ruippeixotog** [comment]
While push updates would surely be the ideal solution, I believe that it would need a lot of work on the backend in order to support it. On the other hand, an auto-refresh feature could be easily implemented on the browser side and it would already help a lot.

After some time working with Kubernetes, having to constantly refresh the page to update the status of the resources is one of the things I still can't get used to. Marathon, on that regard, is much more usable.

**Comment by guenhter** [comment]
Acutally, Kibana makes no real "full-site-update" but just updated some components (changed data). But the settings above defines how frequently the data elements on the page should be refreshed.

**Comment by ruippeixotog** [comment]
It updates only the components using Javascript, so it's indeed not a hard refresh. However, it doesn't update only the changed components; that would require Elasticsearch to provide a way to notify clients about changes in queries. The Kubernetes dashboard can do the same in order to keep a nice UI.

**Comment by maciaszczykm** [comment]
Let's track from #2541.
