### ISSUE TITLE
Dashboard Internal Server Error (500) on deleted resources

### ISSUE THREAD

**Issue by dluc** [kubernetes/dashboard#1608]
##### Environment
Working with minikube

```
minikube version: v0.15.0
Operating system: MacOS
```
##### Steps to reproduce
1. Create a namespace `kubectl create namespace foo`
2. Open the namespace in the dashboard at http://127.0.0.1:8001/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard/#/namespace/foo?namespace=foo
3. Delete the namespace `kubectl delete namespace foo`
4. Refresh the dashboard page in the browser

##### Observed result
Dashboard reported Internal Server Error (500):
```
error_outline Internal Server Error (500)

namespaces "foo" not found
```

##### Expected result
The page should return a 404 error.

**Comment by maciaszczykm** [comment]
It seems to be easy to do, but unfortunately it's not. We are using Kubernetes client, which returns us only error messages and no error code, status etc. To do it we should manually parse JSON responses recieved from API server instead of using Kubernetes client:

``` json
{
   kind: "Status",
   apiVersion: "v1",
   metadata: { },
   status: "Failure",
   message: "the server could not find the requested resource",
   reason: "NotFound",
   details: { },
   code: 404
}
```

It will require major changes and it may not be worth efforts. Using default Kubernetes client seems to be the best solution at the moment. Returning 404 instead of 500 is not the solution neither, we cannot assume, that resource was not found, because other errors may occur too.

@kubernetes/dashboard-maintainers Do you have any other ideas to handle Kubernetes errors better? Should we close it as we won't fix it?
