### ISSUE TITLE
Support running the dashboard in another namespace

### ISSUE THREAD

**Issue by jcassee** [kubernetes/dashboard#1691]
##### Environment
Setup through `kubeadm init`. Installed Dashboard by taking [the resource definition](https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml) and replacing all namespaces with `example`.

```
Dashboard version: 1.5.1
Kubernetes version: 1.5.3
Operating system: Ubuntu 16.04 x86_64
```

##### Steps to reproduce
1. Install dashboard in a different namespace (not `kube-system`.
2. Run `kubectl proxy`
3. Go to `http://localhost:8001/ui`

##### Observed result
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "endpoints \"kubernetes-dashboard\" not found",
  "reason": "NotFound",
  "details": {
    "name": "kubernetes-dashboard",
    "kind": "endpoints"
  },
  "code": 404
}
```

##### Expected result
The dashboard.

##### Comments
Manually changing the namespace in the URL shows the dashboard. It seems I cannot change the `/ui` redirect.

The use-case for running the dashboard in another namespace is keeping a set of resources under version control and using `kubectl apply --purge --namespace example` after every change.

**Comment by maciaszczykm** [comment]
It's Kubernetes issue, as we are not managing `/ui` redirect.

You should put it there https://github.com/kubernetes/kubernetes/issues/new.

**Comment by cheld** [comment]
AFAIK, the UI redirect is hardcoded and only for convenience 

Actually, I did not understand your use case. Isn't kube-system a namespace like any other?

**Comment by jcassee** [comment]
Good question, maybe I'm "doing it wrong". I want to be able to use `kubectl apply --prune` using different file sets, keeping them under version control. It is my understanding that you need to limit `apply --prune` either by label or namespace, or it will remove resources from other file sets. I am using a namespace because it is simpler. The dashboard is in a file set with other resources that should not be in kube-system. And so the dashboard gets created in a different namespace than kube-system.

Does that make sense?

**Comment by floreks** [comment]
As already stated `/ui` endpoint is hardcoded and installed on kubernetes startup. It is not dynamically resolved. You can check it out [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/routes/ui.go). That is because dashboard should be provided by default with most kubernetes deploy tools and it is considered as a system app. 

Dashboard can be created and run in other namespaces without any issues. Only link to access it will be different and you have to do it using this pattern `<master_ip:port>/api/v1/namespaces/<namespace_name>/services/<service_name>/proxy`.

AFAIU `--prune` option is experimental and by default it will first clean up all namespaces of resources in yaml file and then create resources specified in this yaml. It might be limited by some label so only resources matching some label will be deleted. 

I'd not try to create resources with prune option that are in `kube-system` namespace as this is highly risky and might result in deleting some important system apps. It's best to limit creation of user apps to other namespaces and only create/update apps in `kube-system` one by one or using kube addon manager, unless user knows what he is doing.

**Comment by jcassee** [comment]
> As already stated /ui endpoint is hardcoded [...].

Thanks for the link. I guess that means that suggests that the dashboard should be installed automatically? But that is [another issue](https://github.com/kubernetes/kubeadm/issues/62).

> AFAIU --prune option is experimental and by default it will first clean up all namespaces of resources in yaml file and then create resources specified in this yaml. It might be limited by some label so only resources matching some label will be deleted.

Indeed, except that you can limit it to a certain namespace.

> I'd not try to create resources with prune option that are in kube-system namespace as this is highly risky and might result in deleting some important system apps. It's best to limit creation of user apps to other namespaces and only create/update apps in kube-system one by one or using kube addon manager, unless user knows what he is doing.

Exactly, which is why is wanted to use a different namespace.

Thanks everyone for the discussion.
