### ISSUE TITLE
Set default rows displayed

### ISSUE THREAD

**Issue by lypht** [kubernetes/dashboard#1703]
#### Issue details
In the majority of our projects, we have dozens of pods running per namespace.  It would resolve a significant pain point to be able to set a default row return to display all pods (even if scrolling is required) as opposed to cycling through pagination.  A refreshed page always returns 10 rows, limiting quick visual analysis to only the first ten pods.  @pwittrock met you moments ago, and you offered to forward this issue to some helpful peers.  Thanks in advance!
##### Environment

```
Dashboard version: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.5.0
Kubernetes version: 1.5
Operating system: Linux
Node.js version: 6.9.5
Go version: 1.7.1
```

##### Steps to reproduce

Create a namespace with greater than ten pods.
##### Observed result

Pods 11 - n+11 are not visible on the dashboard unless an iterative page is selected.
##### Expected result

Set default rows returned as a static preference, such that all pods in a namespace are viewable from a single page; scrolling is acceptable and encouraged.
##### Comments

Thank you for a great interface.  This is not mission critical, but it will make using the dashboard far more amenable to the UI/UX-inclined.

**Comment by maciaszczykm** [comment]
That's a well described issue, thanks for that. We are planning to implement it.

**Comment by floreks** [comment]
We are actually using query parameters to pass paging settings to the backend. That's why they are not visible in URL. We don't really want to change that because when sorting will be introduced with #1792 then having such parameters in url would enforce same settings for all lists. With query parameters we can sort every list separately, i.e. on workloads page you will be able to sort Pods list by name and Job list by age.

We'll be working on reintroducing selector for number of items per page. It will probably require using cookies to keep user preferences between state transitions. With sorting you will be able to sort Pods by status so it will be easier to find failed Pods.

**Comment by zouyee** [comment]
I think if we want to preserve customized data, maybe we need persistent  storage.

**Comment by cheld** [comment]
Maybe config-map or thirdparty resource?

**Comment by maciaszczykm** [comment]
Will be tracked from #2417.
