### ISSUE TITLE
AppConfig should be able to take arguments from flags

### ISSUE THREAD

**Issue by zhouhaibing089** [kubernetes/dashboard#1865]
Currently, we are using AppConfig to store `ServerTime`, in my opinion, the AppConfig is the way that we want to initialize some data for frontend(correct me if I am wrong).

In the downstream, we want to pass flags for `dashboard`, and possibly different configuration for different realms, and in case the value needs to pass down to frontend, we should be able to initialize appconfig from flags.

**Comment by maciaszczykm** [comment]
>Currently, we are using AppConfig to store ServerTime, in my opinion, the AppConfig is the way that we want to initialize some data for frontend

@zhouhaibing089 What kind of data do you mean here?

> (correct me if I am wrong).

Currently [confighandler.go](https://github.com/kubernetes/dashboard/blob/master/src/app/backend/handler/confighandler.go#L49) returns data for frontend [service.js](https://github.com/kubernetes/dashboard/blob/master/src/app/frontend/common/appconfig/service.js#L39). It allows us to use server time instead of client's (we still would like to get it from cluster somehow).

Recently @cheld introduced also changes allowing to put build data into [service.js](https://github.com/kubernetes/dashboard/blob/master/src/app/frontend/common/appconfig/service.js#L39).

> In the downstream, we want to pass flags for dashboard, and possibly different configuration for different realms, and in case the value needs to pass down to frontend, we should be able to initialize appconfig from flags.

As far as I understand you are trying to customize Dashboard for your own needs. We have to understand better your requirements to tell if we can upstream your proposal.

**Comment by zhouhaibing089** [comment]
> What kind of data do you mean here?

mostly I mean configuration. For example, I want to change the action bar to add a link to somewhere(background: we have legacy PaaS system, and it will jump into kube dashboard when user wants to use container to deploy workloads, and in this case, we want to add a link to go back, the url itself might be different in different environments(QA, staging, preprod, etc)). So specifically, in my current situation, I want to pass a url to service.js.

 > As far as I understand you are trying to customize Dashboard for your own needs. We have to understand better your requirements to tell if we can upstream your proposal.

The use case is mentioned above.

@maciaszczykm I am not sure what's the best way to do that in my case(there might be more cases following), and I just see `appConfig.json` request, and guess it might be a good place, thanks anyway.

**Comment by maciaszczykm** [comment]
@zhouhaibing089 Okay, now I understand. Since you have to create fork anyways (to display link) I suggest to introduce your own parameter only on your fork. To do it just add new parameter to `dashboard.go` (it is easy, just check other params here) and send this value to the frontend using `confighandler.go`. Then you will be able to read it from `service.js`. It should not be hard to do, but of course if you will need our assistance we will help.

It seems to small and user-specific feature to implement it on upstream.

Good luck!

**Comment by zhouhaibing089** [comment]
@maciaszczykm yeah, I already did it.

The intention of this issue is mostly about:

1.  is it the best place to do it?
2.  can we make the current code more extendable(the current implementation does not care about flags anyway).

**Comment by maciaszczykm** [comment]
@zhouhaibing089 Currently it seems to be the best place. If you want to reduce merge effort you may want to create separate files, that you will use only downstream, but we are also open to contributions. If you have an idea how can you make this mechanism generic, so other people will make use of it then go for it. Any valuable contributions are welcomed.

**Comment by floreks** [comment]
These files are not likely to be changed on our side so I wouldn't worry about merge issues :smile:  You could of course try to create new files like @maciaszczykm  suggests. If we could find some more generic approach to this or more common use cases for people then we will be happy to push that upstream.

**Comment by zhouhaibing089** [comment]
@maciaszczykm @floreks thanks folks, I am doing exactly the same as you guys suggested, I've added another `ConfigExtension` type in another file, and make it part of `AppConfig`.

I think I already get the answer, I will look into how to make such process generic and propose a PR accordingly.

Just leave it open for some time.

**Comment by maciaszczykm** [comment]
@zhouhaibing089 Are there any action items left?

**Comment by zhouhaibing089** [comment]
@maciaszczykm thanks for checking, I was planned to do some change like: the AppConfig should take `flagset` as an argument, but that's not so important, or I even do not think there is a strong agreement, so let's close this to get rid of interrupting when looking for issues.
