### ISSUE TITLE
Card footer's top border should not be shown if footer has no content

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#1893]
Creating this issue to discuss how we can improve filtering UI:

![image](https://cloud.githubusercontent.com/assets/2823399/25518916/fd47048e-2bf5-11e7-97b0-050f896f0a02.png)

Two things come to my mind:

- [x] styling of filtering input
- [ ] footer top border should not be shown if footer has no content

**Comment by danielromlein** [comment]
Since we already have "Search" at the global level I think it would be clearer to users if we went with the term "Filter" for this. We could either use the filter icon, 
![filter](https://cloud.githubusercontent.com/assets/5114858/25585639/9d09b6e0-2e69-11e7-8278-829e10c95a8f.png)
or if we think that wouldn't be obvious enough, could add a label of "Filter" next to the input. 

The Material spec for the styling of the input is that it should be underlined, not have the outline all the way around:
![screen shot 2017-05-01 at 12 20 28 pm](https://cloud.githubusercontent.com/assets/5114858/25585656/b1449080-2e69-11e7-8e26-fa7c08a9ba4a.png)

Sorry for not responding sooner @maciaszczykm & @floreks! 
WDYT? I can mock this up if it'd be helpful.

**Comment by floreks** [comment]
I like this answer that points out the difference between "Filter" and "Search" taken from [here](https://ux.stackexchange.com/questions/4752/search-vs-filter-what-is-the-difference).

>I guess filtering provides a specific impression whereas searching provides a generic impression. What I mean by impression is the human impression a user gets while performing the said action. For example: lets say to pick an apple from a basket full of fruits and vegetables;
>
>filter: filter by 'fruits' and pick an apple
>search: search for an apple (when you don't know whether an apple is a fruit!)

In our case both on list level and global level we are actually using Filtering by name. Search would be more sophisticated and consider not only name but all the data that matches search string. 

This also shows the difference in the UI between Filter and Search
![image](https://cloud.githubusercontent.com/assets/2285385/25698661/fd2719ac-30bf-11e7-8500-4f4aad1e26f1.png)

We might want to think about that when redesigning our "Search" action. Maybe at first it should be named Filter on both levels with indicator that it is filter by name only?
