### ISSUE TITLE
Global search UI

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#1943]
Creating this issue to discuss how we can improve global search UI:

![image](https://cloud.githubusercontent.com/assets/2823399/25996159/11071b00-3716-11e7-8778-2d52aa4fabd3.png)

Checklist:

- [ ] handling empty search and go back button (mentioned in https://github.com/kubernetes/dashboard/pull/1895#pullrequestreview-37794713)

@danielromlein We hope for your suggestions here. You can deploy new HEAD release to check how it works. Ping me on Slack if you will need help.

**Comment by danielromlein** [comment]
Sounds good! I will try to get the HEAD release deployed so I can check it out. I'll take a look at this all and provide feedback on Monday. Thank you!

**Comment by maciaszczykm** [comment]
@danielromlein Great! Looking forward to it.

**Comment by therc** [comment]
Another item for the checklist: search by node, service or pod IP address.

**Comment by Justkant** [comment]
Can we have the search bar merged with the blue bar ?
Strange to left that much free space on the blue bar

**Comment by maciaszczykm** [comment]
@Justkant Go to details page of pod for example and you will see breadcrumbs on the left and action buttons on the right. There is no space to do so.

**Comment by floreks** [comment]
Also blue bar changes based on the current state (list view, detail view). White bar is a global bar. Search is a global action. That is why search is on white bar.

**Comment by Justkant** [comment]
@maciaszczykm I understand the space problems, but we can probably work around that using the same logic as the gcloud console top bar. (On small screen, it shows a button instead of the search bar)

I added some screenshots to help see what I mean.

Medium screen size:
- Dashboard: <img width="1680" alt="capture d ecran 2017-08-03 a 14 17 35" src="https://user-images.githubusercontent.com/3009753/28921655-21185c8e-7857-11e7-8623-fac21fa05923.png">
- Gcloud: <img width="1677" alt="capture d ecran 2017-08-03 a 14 17 51" src="https://user-images.githubusercontent.com/3009753/28921673-32fc851a-7857-11e7-8e91-0e44af48e482.png">

Small screen size:
- Dashboard: <img width="724" alt="capture d ecran 2017-08-03 a 14 18 03" src="https://user-images.githubusercontent.com/3009753/28921740-715c29b4-7857-11e7-9cd8-5f8deeff902e.png">
- Gcloud: <img width="723" alt="capture d ecran 2017-08-03 a 14 18 10" src="https://user-images.githubusercontent.com/3009753/28921756-7dadd596-7857-11e7-8bfb-32a5bf54250a.png"> <img width="723" alt="capture d ecran 2017-08-03 a 14 18 23" src="https://user-images.githubusercontent.com/3009753/28921755-7dadc9de-7857-11e7-83d1-8ebcab2eae7e.png">

What do you think of this idea ? Is it feasible ? 🤔 
And thanks for the work on this project, keep it up ✌️

**Comment by floreks** [comment]
Even if this is feasible then IMO moving `Global Search` action to a view specific bar is not a good idea.

First bar - Application wide - Global actions present
Second bar - View specific - Different actions available for different views

**Comment by Justkant** [comment]
No problem, I understand the distinction 😄 
I just liked the old configuration with the single bar and wanted to try to get this again.

Keep up the good work!

**Comment by danielromlein** [comment]
+1 @floreks. I think the hierarchy we've imposed of top --> global actions and secondary bar --> object-specific actions is an important UI distinction to maintain unless we plan on re-thinking the information architecture. Thank you for the suggestion though @Justkant!
