### ISSUE TITLE
How to create a different user than admin to access dashboard?

### ISSUE THREAD

**Issue by endejoli** [kubernetes/dashboard#1991]
We have a kubernetes cluster up and running. we have added dashboard as file. Currently we are using 'admin' user for authentication. How can I setup a new user for authentication ?

**Comment by floreks** [comment]
I can only provide some general description because there any many ways to do that.

Dashboard now takes header in request that should look like `Authorization: Bearer <token>` then strips down token from it and passes it to apiserver during every call. Token can be validated by apiserver in many different ways. You can read more about that in here: https://kubernetes.io/docs/admin/authentication

For testing I've created new service account and used token from secret assigned to it. Normally SA are for applications and you should use other ways to authenticate users. For chrome browser you can try using Requestly plugin for tests. It is good to have some auth proxy before dashboard that will alter the request header for you.

**Comment by cheld** [comment]
I try to give a high level answer:

Currently, Dashboard has not its own authentication mechanism. Instead, we expect that Dashboard is accessed through apiserver e.g. http://apiserver/ui

The idea is to set up apiserver and Dashboard acts accordingly. In parctice it is a little bit more complicated because Dashboard used a super-user to access the apiserver. Therefore, we use the user token in the request header to do the correct user authentication with the apiserver.

hope this helps

**Comment by fwynyk** [comment]
I guess @endejoli would like to manage users via dashboard. Just took a look and found we have [this](https://github.com/kubernetes/dashboard/blob/master/docs/design/access-control.md) proposal by @mlamina which is the solution for this issue. It's also my wish to have this access control working soon.

**Comment by maciaszczykm** [comment]
@endejoli I believe, that @floreks and @cheld already answered your question.

@fwynyk It will be covered in https://github.com/kubernetes/dashboard/issues/1441.

**Comment by hareeshrao4839** [comment]
kubectl create clusterrolebinding cluster-admin --clusterrole=edit --user=user1 --user=user2 --group=group1

**Comment by TonyBarganski** [comment]
@harwwshrao4839 can you expand on your answer?
