### ISSUE TITLE
can not visit dashboard service 

### ISSUE THREAD

**Issue by justlooks** [kubernetes/dashboard#2135]
Environment:

Kubernetes version (use kubectl version): v1.7.0
Cloud provider or hardware configuration**:
OS (e.g. from /etc/os-release): CentOS 7
Kernel (e.g. uname -a): Linux k8s-master 3.10.0-514.6.2.el7.x86_64
Install tools: Kubeadm
Others:
docker version : Docker version 1.12.6,
My RPM version :
docker-1.12.6-16.el7.centos.x86_64.rpm
kubectl-1.7.0-0.x86_64.rpm
kubernetes-cni-0.5.1-0.x86_64.rpm
kubeadm-1.7.0-0.x86_64.rpm
kubelet-1.7.0-0.x86_64.rpm

I installed dashboard ,but why i can not visit ?

[root@k8s-master ~]# kubectl create -f https://git.io/kube-dashboard
serviceaccount "kubernetes-dashboard" created
clusterrolebinding "kubernetes-dashboard" created
deployment "kubernetes-dashboard" created
service "kubernetes-dashboard" created
[root@k8s-master ~]# kubectl get services --all-namespaces
NAMESPACE     NAME                   CLUSTER-IP     EXTERNAL-IP   PORT(S)         AGE
default       kubernetes             10.96.0.1      <none>        443/TCP         5d
kube-system   kube-dns               10.96.0.10     <none>        53/UDP,53/TCP   5d
kube-system   kubernetes-dashboard   10.96.241.25   <none>        80/TCP          1m

[root@k8s-master ~]# curl 10.96.241.25:80/ui

/sig need-help

**Comment by justlooks** [comment]
> # kubectl get services/kubernetes-dashboard  --namespace kube-system -o wide
> NAME                   CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE       SELECTOR
> kubernetes-dashboard   10.99.241.194   <nodes>       80:32469/TCP   1m        k8s-app=kubernetes-dashboard
> 
> # ping 10.99.241.194
> PING 10.99.241.194 (10.99.241.194) 56(84) bytes of data.
> ^C
> --- 10.99.241.194 ping statistics ---
> 3 packets transmitted, 0 received, 100% packet loss, time 1999ms
> 
> [root@k8s-master ~]# telnet 10.99.241.194 32469
> Trying 10.99.241.194...

**Comment by floreks** [comment]
First check if dashboard pod is running with `kubectl get pods -n kube-system` then show us logs from the dashboard pod with `kubectl logs <pod_name>`.

Second thing is that from the machine where you have run `kubeadm` you won't be able to access `<service_ip>:<port>` (10.96.241.25:80). This address is normally accessible only from inside the cluster (from inside the container to be specific). Additionally `/ui` endpoint is only exposed by kubernetes apiserver. You'd need to run `kubectl proxy` command to expose apiserver and then try to access it since `kubeadm` does not expose apiserver on insecure port.

There are already many resolved issues similar to this one. There is also `Usage` section and `Troubleshooting Guide` in our documentation that you should take a look at.
