### ISSUE TITLE
Feature Request: Exec /bin/ash (for alpine images)

### ISSUE THREAD

**Issue by mrl045** [kubernetes/dashboard#2305]
##### Environment

```
Dashboard version:  1.6.3
Kubernetes version: v1.5.1
Operating system: Container Linux by CoreOS 1465.6.0 (Ladybug)
Node.js version:
Go version:
```

##### Steps to reproduce
Open the Kubernetes dashboard and browse to pods (under workload). Click on a alpine based pod. Use the exec button on top of the dashboard.

##### Observed result
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"exec: \\\"bash\\\": executable file not found in $PATH\"\n"
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"exec: \\\"sh\\\": executable file not found in $PATH\"\n"

##### Expected result
Run another exec for /bin/ash executable to get access.

##### Comments
No comments

**Comment by kachkaev** [comment]
Hi @floreks! I faced exactly the same issue a few days ago and mentioned it in https://github.com/kubernetes/dashboard/issues/1345#issuecomment-323670201. Turns out there exists https://github.com/kubernetes/dashboard/issues/2029 where this problem is being tracked, so feel free to subscribe to updates there. This issue is likely a duplicate.

**Comment by floreks** [comment]
Closing as we'll track is from #2029.
