### ISSUE TITLE
Add instructions and help links to explain the authentication options

### ISSUE THREAD

**Issue by rahuldhide** [kubernetes/dashboard#2433]
Here is the proposal for the Login screen based on these requirements-
 https://github.com/kubernetes/dashboard/wiki/Access-control#login-view

**Token**
Every Service Account has a Secret with valid Bearer Token that can be used to log in to Dashboard. To find out more about how to configure and use Bearer Tokens, please refer to the [Authentication](https://kubernetes.io/docs/admin/authentication/) section.

**Kubeconfig**
Please select the kubeconfig file that you have created to configure access to the cluster. To find out more about how to configure and use kubeconfig file, please refer to the [Configure Access](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/) to Multiple Clusters section.

**Comment by maciaszczykm** [comment]
Sounds good. Do you plan to prepare mockups with text placed on them?

**Comment by floreks** [comment]
It's a good start. We will work on the text itself. Mockups would be extremely helpful here.

**Comment by cheld** [comment]
We could add the text like in the creation dialog.

**Comment by rahuldhide** [comment]
Attaching the mockup.
![kdash_signin](https://user-images.githubusercontent.com/30275450/31506355-0cd860e6-af2c-11e7-8f39-be1e3f3666dd.png)

**Comment by maciaszczykm** [comment]
Looks great.

**Comment by floreks** [comment]
If we would stick to the current design then this change looks nice. I do have however this feeling that we could give login view another chance and completely redesign it. We are open to anything and we do not have to stick to existing template. I guess it would be nice to have and compare more options.

I have had a quick look at some example login view templates. Keep in mind that these are only templates and they would have to be tailored to our needs and to material design. I'm just thinking about elements positioning and overall look and feel, so don't project it 1:1 and think about how exactly this look would fit to Dashboard.

1. https://support.advorto.com/hc/article_attachments/115010222507/Login.png
2. https://i.pinimg.com/originals/e9/43/c7/e943c793205b3f947509fb20ec9017f9.jpg
3. https://www.strapui.com/wp-content/uploads/2015/04/Screen-Shot-2015-05-08-at-6.17.00-pm.png
4. https://dcrazed.com/wp-content/uploads/2015/05/css3-login-form-with-signup.jpg

These 2 are supposed to be based on material design.
1. https://mir-s3-cdn-cf.behance.net/project_modules/fs/6eaff048611705.58a6ecd105fa5.jpg
2. https://assets.materialup.com/uploads/495f349a-9e37-45b2-b2b8-83dd010e9137/login.png

There are couple of interesting points:
- Using tabs or buttons instead of using radio buttons to change login method
- Space separated from input form just for text
- Better available space usage (more modern look)
- Currently we do not even have kubernetes logo anywhere. Given options make better use of it and of background to attract user.

**Comment by cheld** [comment]
UX design in create dialog:

![create-dialog](https://user-images.githubusercontent.com/7448799/31550539-fd75b318-b031-11e7-8c4e-b0bc7be9b10f.png)

Proposal is also very good

**Comment by maciaszczykm** [comment]
@cheld In my opinion we could improve it a bit too. For example radio buttons at the top are not nice. I would prefer tabs here.

**Comment by rahuldhide** [comment]
Great feedback and good samples @floreks. I will create some proposals and share those soon.
