### ISSUE TITLE
compatibility with older k8s versions

### ISSUE THREAD

**Issue by ReSearchITEng** [kubernetes/dashboard#2531]
##### Environment
```
Dashboard version: 1.7.1 (Git Commit: d0cd1893cc062d06dee2170b5ef6fde1867ae93c )
Kubernetes version: 1.6.11
Operating system: Centos 7
Node.js version:
Go version:
```

##### Steps to reproduce
Browse default page (Overview).

##### Observed result
Overview page does not work, (probably tries to show resources which do not exist in v1.6.11, like CronJobs)
Also CronJobs page does not work. (http://......./#!/cronjob?namespace=default )

##### Expected result
Show the relevant resources for the specific version.

**Comment by maciaszczykm** [comment]
Cron Jobs will be part of Dashboard 1.8 release. Right now they are available only with HEAD builds:
https://github.com/kubernetes/dashboard/wiki/Installation#development-release

Dashboard 1.7 may not work with Kubernetes 1.6 due to other reasons. We are too short of resources to support older versions. You can find our compatibility matrix below:
https://github.com/kubernetes/dashboard/wiki/Compatibility-matrix

It would be extremely helpful if you could investigate this issue on your own and provide a fix for us, but we will not spend time to fix it. Our main target at the moment is to provide support for Kubernetes 1.8 in Dashboard 1.8.

**Comment by maciaszczykm** [comment]
I just noticed, that you are already using latest master version. It will not work with cluster 1.6.x because of many reasons, not only cron jobs. Migration from TPR to CRD will also be problematic and we are going to migrate API versions too.
