### ISSUE TITLE
User "system:serviceaccount:kube-system:kubernetes-dashboard" cannot list ...

### ISSUE THREAD

**Issue by KeithTt** [kubernetes/dashboard#2552]
kube ver: 1.8.2
docker ver: 17.10.0-ce
dashboard ver: 1.7.1

There were many brown warnings in the UI page, and report that can not list any resources...

**Comment by maciaszczykm** [comment]
This is not an issue. Read our [wikis](https://github.com/kubernetes/dashboard/wiki) and Kubernetes documentation, because you need to setup access control in your cluster. Brown/orange warnings are coming from Kubernetes apiserver and it means that you do not have specific privileges (skipped auth/not enough access rights).
