### ISSUE TITLE
Fail to login - Access Control is not helping

### ISSUE THREAD

**Issue by ikus060** [kubernetes/dashboard#2558]
```
Dashboard version: recommended
Kubernetes version: v1.8
Operating system: debian Stretch
Node.js version: ?
Go version: ?
```

I've created a new kubernetes cluster and added the dashboard. I have some trouble to log into the dashboard. Seam I'm not the only one. See #2524, #2474, #2476 and probably more.

Plz don't refer me to the access control page (https://github.com/kubernetes/dashboard/wiki/Access-control) I've already read it.

Is it possible to provide more explicit information about how to make the login work ?
e.g.:
1. Is is possible to use the kubeconfig authentication ? If so, is it possible to provide a sample or to explain where to get it from ?
2. Token authentication seems to be the new thing. But after reading dozen pages on the subject, I still don't understand how to generate a new one for myself that allows me to log in to the dashboard with the right permission. Is it possible to describe the steps to generate such token ?

Thanks,

**Comment by floreks** [comment]
> Is is possible to use the kubeconfig authentication ? If so, is it possible to provide a sample or to explain where to get it from ?

As per documentation says:
> Only authentication options specified by --authentication-mode flag are supported in kubeconfig file.

By default `--authentication-mode` is set to `token`, meaning that kubeconfig file has to be configured to use token based authentication. More information about kubeconfig file can be found [here](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/).

> Token authentication seems to be the new thing. But after reading dozen pages on the subject, I still don't understand how to generate a new one for myself that allows me to log in to the dashboard with the right permission. Is it possible to describe the steps to generate such token ?

We deliberately do not provide exact steps of how to "generate" token as there are many ways of getting one. It is important that user reads Kubernetes documentation first and understands how different authentication and authorization mechanisms work in order to be able to use them. Dashboard tries to mimic behavior of `kubectl` which also supports `--token` parameter that can be used for authentication.

You should start by reading:
- [Service Account Tokens](https://kubernetes.io/docs/admin/authentication/#service-account-tokens)
- [Role and ClusterRole](https://kubernetes.io/docs/admin/authorization/rbac/#role-and-clusterrole)
- [Service Account Permissions](https://kubernetes.io/docs/admin/authorization/rbac/#service-account-permissions)

Creating and using service accounts is the easiest way of getting tokens, **but not the only one**. There are more ways described in Kubernetes documentation. We also do not want to copy & paste information that can be found in Kubernetes documentation, but rather point user to it by providing necessary links in our documentation.

**Comment by ikus060** [comment]
I do understand your point, but when trying to setup a kubernetes cluster for the first time, I may not want to know in depth how everything is working. Also, the authentication system seam to be very sophisticated. And before trying to learn how the authentication is working, I want to get into the dashboard.

**Comment by floreks** [comment]
If you just want to access Dashboard with all privileges you can always try: https://github.com/kubernetes/dashboard/wiki/Access-control#admin-privileges

After applying this you can use `Skip` button and have full access to all resources. Then you can take some time to learn how to actually configure some SA and set required privileges by yourself.

**Comment by floreks** [comment]
I think everything is clear here. Closing.
