### ISSUE TITLE
Dashboard show pod that is deleted using kubectl

### ISSUE THREAD

**Issue by likunbyl** [kubernetes/dashboard#2600]
##### Environment
```
Dashboard version: 1.7.1
Kubernetes version: 1.7.8
Operating system: coreos1298.5.0
```

##### Steps to reproduce
1. found a pod in complete state.
2. use kubectl to delete it.
3. from kubectl get pod output it's disappear.
4. form dashboard pods page or overview page, it's still there

##### Observed result
```
$ kubectl get pod
NAME                                           READY     STATUS    RESTARTS   AGE
dunking-hedgehog-helmet-2935732138-n4wr2       1/1       Running   0          7d
kube-controller-az01.wjs.lab.com       4/4       Running   17         4d
kube-controller-az02.wjs.lab.com       4/4       Running   1          4d
kube-controller-az03.wjs.lab.com       4/4       Running   21         30d
kube-proxy-az04.wjs.lab.com            1/1       Running   2          30d
kube-proxy-az05.wjs.lab.com            1/1       Running   1          30d
kube-proxy-az06.wjs.lab.com            1/1       Running   1          30d
kube-system-tomcat-official-3473459199-pl709   1/1       Running   0          7d
smelly-pig-mysql-2041189866-22kql              1/1       Running   0          14d
```

![image](https://user-images.githubusercontent.com/20676359/33054033-d2eb3408-ceb1-11e7-8668-cc41343e3419.png)

##### Expected result
kubectl and dashboard should output the same thing.

**Comment by floreks** [comment]
Works as expected. We are actually showing output of `kubectl get pod --show-all` which includes also pods in a `Completed` state.

**Comment by cheld** [comment]
@floreks IT IS UX issue. Could we show different icon? Or different color?

**Comment by cheld** [comment]
@floreks we could also add a button that hides some kind of pods. We had similar issue with replica sets

**Comment by floreks** [comment]
> @floreks it is UX issue. Could we show different icon? Or different color (e.g. grey)?

I don't think this is an issue. We do follow kubectl behavior to some extent, but sometimes we have to do something a bit differently like in this case. We could think of different icon if we can find one. Gray color is reserved for pending icon so it would be misleading. IMO current icon is still correct because it shows that everything is ok with pod. It completed its job and is now in `Completed` state. 

> @floreks we could also add a button that hides some kind of pods. We had similar issue with replica sets

With replica sets there was actually no issue. We have followed `kubectl` behavior. What we could do is to add switch button on top of pod list that would be enabled by default and apply `--show-all` to result list. For me user experience of `kubectl get pod` was actually a bit misleading because I did not see the completed pods and I have had to look into documentation to see how to show all of them.
