### ISSUE TITLE
Dashboard features for non-admin developers: Integrate dashboard login with GitHub oauth

### ISSUE THREAD

**Issue by cohadar** [kubernetes/dashboard#2621]
I am going to describe the ideal scenario for working with dashboard when you have lots of people that need to access it, with different privilege levels.
I know these things are rather subjective, but it seems to me this setup would work for 80% of people using k8s out there.

You host a dashboard like any other app in your k8s cluster: https://dashboard.my-k8s-cluster.com
This address is https with valid cert (let's encrypt is good enough)
Ingress actually points to GitHub ouath2 proxy, so only developers that belong to your org can SSO.
When developer logs in with oauth2 proxy, the proxy id (GitHub id) is automatically used as a dashboard user id. 

On production cluster:
Using RBAC rules you limit developers to read-only access on namespaces they are using. (so they can view logs and state of their apps)
Namespace dropdown selection shows only the namespaces developer can actually see!

On dev cluster:
Using RBAC you give developers admin access, but again, only in their own namespaces.

===================================================================

This is imho a much more user friendly solution than hosting a dashboard through k8s api, or using 'kubectl proxy' and those long and ugly path strings.

I think this whole 'SSL login' solution that came in dashboard 1.7 is a step in a wrong direction!
Why provide SSL protection to dashboard when nginx-ingress can do it for you?
Why expose dashboard through API proxy when you can host it in k8s just like any other app?

Proper login support for oauth2 makes the above 'hacks' meaningless + people can choose their own nice urls for dashboard + use their own cert.

**Comment by floreks** [comment]
The problem here is that Dashboard has to rely fully on auth mechanisms provided by kubernetes API server. In order to achieve such functionality we'd need to:

1. Configure API server to use external identity provider
2. Somehow use that knowledge and integrate Dashboard with that.

API is somewhat limited here as it does not allow us to check what kind of auth mechanism is enabled in API server. User would have to manually provide same options in both places. We can not even check username tied to the token that is used to log in as API does not have such option. Dashboard only acts as a proxy here and passes all auth information on every request straight to API server. It decides whether or not allow access.

> This is imho a much more user friendly solution than hosting a dashboard through k8s api, or using 'kubectl proxy' and those long and ugly path strings.

I think this whole 'SSL login' solution that came in dashboard 1.7 is a step in a wrong direction!
Why provide SSL protection to dashboard when nginx-ingress can do it for you?
Why expose dashboard through API proxy when you can host it in k8s just like any other app?

In 1.8 we have added option to show login view when Dashboard is not served over HTTPS (backend), however when exposing it using ingress, frontend should be still accessed over HTTPS. 

Many people are forgetting that even though Dashboard **can** be exposed using ingress, it is not the only way to expose it. For all the people that would like to simply expose it using NodePort, `kubectl proxy --address` or even directly expose some API server proxy path, we have to ensure that credentials provided on log in screen will not be sent in plain text over network. 

> Proper login support for oauth2 makes the above 'hacks' meaningless + people can choose their own nice urls for dashboard + use their own cert.

This is still possible when using alternative setup. You can simply configure auth proxy in front of Dashboard that will pass valid bearer token accepted by API server in request header.

**Comment by floreks** [comment]
Closing as we have a tracking issue for it #2353.
