### ISSUE TITLE
OIDC without a proxy

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/dashboard#2630]
This is a feature request to support using OIDC without needing a proxy. 

On #1589 it's noted that:

> You can't use OIDC directly. You can however configure proxy server that will require logging in and will pass bearer token to dashboard. Dashboard checks for Authorization: Bearer <token> in a request header and uses it to authorize user.

A users expectation for managing infrastructure is usually to login with username and password. With a company this is often via a companies corp login page. AWS, Azure, Google, and even OpenStack allow you to login in a simple common way. This idea is to bring that _experience_ to the dashboard.

Note, this makes the assumption that many people won't use the CLI. Sometimes this will be management and other times people who use UIs and not CLIs to do management.

Ideally, if k8s uses OIDC this is either autodetected for a redirect if there is no token present or someone can configure OIDC for dashboard.

The experience could be an automatic redirect or a notice that one needs to login and lets them click a button to do so.

The focus of this request is on improved user experience.

cc: @venezia

**Comment by floreks** [comment]
We were thinking on such feature during login feature implementation, however right now there is no way to autodetect how kubernetes is configured. I'd prefer to use k8s API to autodiscover this and be able to use external IdP to authenticate user. 

We constantly have this feature in mind but we want to make it easy to configure and use. Not having a database puts some constraints on Dashboard.

**Comment by mattfarina** [comment]
A couple things come to mind immediately:

1. Could someone pass in the OIDC config via environment variable or some other form of configuration? This could be used if provided and skipped if not. Wouldn't that be easier than setting up a proxy today? I know it would be pretty easy to do with helm/charts for folks who go that route.
1. Would it be worth filing and issue for and building an API upstream to consume these details?

**Comment by venezia** [comment]
I think its probably worthwhile for the API server to have an endpoint/url/etc. that indicates to applications like kubernetes-dashboard that OIDC is enabled and where to send users to get authenticated.  

Right now there's only support for a single OIDC URL, so its would be somewhat straightforward as to "where to go", but i agree this is beyond the singular scope of dashboard - we need to add more features to the api server as well.

I think there's a lot of UX value in having an ability to "vanilla" browser be able to reach the API server (proxied or not) for things like this.  Installing an SSL certificate for authorization is not user-friendly typically (this does work for API server, but not kubernetes-dashboard), and requiring extensions like requestly to set bearer token headers (instead of HTTPS-protected cookies) seems to be way too much of a hassle for mere mortals, which I understand is the thrust of this ticket.

For me, its not just kubernetes-dashboard, but also possibly things like grafana suites that are appropriate for the given user.  Dreaming a bit, what if we wanted to give people an app (ios/android) that's similar to dashboard - I see this as more than just web browser support, but the general "How do we bring authorization/authentication systems that kubernetes support, and make them easy for browsers and apps to consume"

**Comment by floreks** [comment]
> 1. Could someone pass in the OIDC config via environment variable or some other form of configuration? This could be used if provided and skipped if not. Wouldn't that be easier than setting up a proxy today? I know it would be pretty easy to do with helm/charts for folks who go that route.

The issue here is that without proper core API Dashboard would need to handle authentication with external IdP on its own. We really want to avoid having to copy paste same arguments from apiserver binary to Dashboard.

> 2. Would it be worth filing and issue for and building an API upstream to consume these details?

AFAIK there were plans to expose information we need for such feature. I'm not sure if this is an ongoing task. Feel free to ask core guys for more information.

@venezia 

First part of bringing seamless login experience is for kubernetes to expose API that will allow it. We want Dashboard to be a UI reflection of kubernetes API and use auth mechanisms offered by it without having to move or copy logic from the core.

I think that currently configuring reverse proxy that will handle authentication is not that much of a hassle.

**Comment by floreks** [comment]
Closing as we have a tracking issue for it #2353.
