### ISSUE TITLE
Detailed beginner usage.

### ISSUE THREAD

**Issue by ronaldpetty** [kubernetes/dashboard#2643]
##### Environment

```
Dashboard version:
Kubernetes version: 1.8.4
Operating system: Ubuntu 16.04
Node.js version:
Go version: 1.8.3
```

##### Steps to reproduce

kubeadm init
kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
kubectl proxy

##### Observed result

Get kubeconfig/token signin page (can skip)

##### Expected result

Get dashboard with namespace access

##### Comments

While we can skip, wasn't the point of the kube-proxy to use the original credentials (set up by kubeadm)?  I know they are different products, but suspect its common to want to use both out of the box.  Maybe just a link to how to use dashboard from at least one know k8s install technique (or fill in the required steps for a typical running cluster)?

One other observation, kube-proxy if used to allow remote access, the form requires the use of a file browser which is local to the proxy not the client browser.  There is no way to type in a local file to the proxy without being on the same machine.

**Comment by ronaldpetty** [comment]
Noticed that if you use the kubeadm generated token, you can't sign-in, but you get no error.  

```
$ sudo kubeadm token list
[sudo] password for user: 
TOKEN                     TTL       EXPIRES                     USAGES                   DESCRIPTION                                                EXTRA GROUPS
cf7fac.abad56b5a672097d   21h       2017-12-05T11:12:26-08:00   authentication,signing   The default bootstrap token generated by 'kubeadm init'.   system:bootstrappers:kubeadm:default-node-token

$
```

If you change the length of the token it does produce an error.

**Comment by floreks** [comment]
> While we can skip, wasn't the point of the kube-proxy to use the original credentials (set up by kubeadm)? I know they are different products, but suspect its common to want to use both out of the box. Maybe just a link to how to use dashboard from at least one know k8s install technique (or fill in the required steps for a typical running cluster)?

One thing to get on the same page first. `kube-proxy` != `kubectl proxy`. First one is responsible for creating firewall rules to enable traffic between nodes, pods, etc. Second one creates authenticated secure tunnel between client machine and apiserver.

I understand why'd you think that it should work this way, however kubernetes does not work in a way to allow exposing privileges further to the application accessed over service proxy. It would be very insecure. Let's say that someone with access limited to single namespace deployed simple web app in it and somehow 'tricked' you to open it. You are using `kubectl proxy` as admin to access this app over apiserver service proxy. You do not know that underneath there is a code that tries to create another admin account that will allow attacker to take over your cluster.

Normally applications work in a sandbox. Dashboard has it's own service account with minimal set of privileges in order to minimize the risk of privilege escalation.

To sum up, kubectl proxy only authenticates you with apiserver, however all the applications accessed using apiserver service proxy should not inherit these privileges. There was some discussion in core to allow apiserver to act as a transparent proxy, but I think it was dropped. 

> Maybe just a link to how to use dashboard from at least one know k8s install technique (or fill in the required steps for a typical running cluster)?

In our documentation, we have described couple of ways to access Dashboard. There is even section describing how to grant Dashboard admin privileges if needed.
https://github.com/kubernetes/dashboard/wiki/Access-control

I think that there is no such thing as 'typical steps to access cluster' because there are too many use cases of how people are using their clusters and how they are separating logic/applications/users in them. We have provided all the details and links to k8s core documentation required to understand how to create and configure simple Service Account and then use it to access Dashboard.

> One other observation, kube-proxy if used to allow remote access, the form requires the use of a file browser which is local to the proxy not the client browser. There is no way to type in a local file to the proxy without being on the same machine.

I don't understand what you mean here. Can you elaborate?

> Update: If using proxy, the error messages only seem to show on localhost and not the external ip.

Taken from our documentation ([Accessing Dashboard](https://github.com/kubernetes/dashboard/wiki/Accessing-Dashboard---1.7.X-and-above#kubectl-proxy)):
> NOTE: Dashboard should not be exposed publicly using kubectl proxy command as it only allows HTTP connection. For domains other than localhost and 127.0.0.1 it will not be possible to sign in. Nothing will happen after clicking Sign in button on login page.

**Comment by ronaldpetty** [comment]
Thanks @floreks for the detailed response.  I will think harder on things.

I did mean kubectl proxy not kube-proxy (mental slip).  To elaborate, if you set up kubeadm on a single node (laptop vm), then tried to use the laptop (non-vm) browser; the screen asks for a config or token, you can't enter the config info from the VM file path only the laptop, which doesn't have it.  Not a big deal, but seemed like I should be able to type in a path on the VM and not just upload from the laptop.

Thanks for the help, will study some more, just trying to simplify simple things, I think people expect the dashboard to just work (including myself) when using the typical tools like kubeadm/kop/etc.  Maybe there is enough detail, but the reality is for me, there is way more to setting up the dashboard because of security than actually using the dashboard; which I think is inverted.

**Comment by floreks** [comment]
> Not a big deal, but seemed like I should be able to type in a path on the VM and not just upload from the laptop.

It will always be relative to the client machine that is running frontend part of the app. There is no way to make it be relative to the node where pod is running as it is running in a sandbox and does not have access to host.

**Comment by floreks** [comment]
Are there any action items for us here or can we close?

**Comment by ronaldpetty** [comment]
Hi @floreks , I suppose not, but would recommend details on how to install via the normal kubeadm installation.  I have taught k8s to many people and not a single person is able to successful install the dashboard without a lot more background.  Not saying it isn't warranted, but I think in general all standard apps should work out of the box on a standard install.  I know kubeadm is not 'official' standard, but unless someone else has a better idea I think it is for most.

Keep up the good work!  If you like I could do a PR for that and see what you think.

**Comment by floreks** [comment]
It is true that Dashboard usage is not that easy at first. The installation process is simple but logging in requires reading and getting familiar with kubernetes concepts of authentication and authorization. Also we can not compare `kubeadm` to `Dashboard` as they are very different. One is a cluster provisioner and the other one is a webapp. It is intended for `kubeadm` to give you full access to the cluster after installation and it is not intended to grant Dashboard (or any other webapp) full access to the cluster. 

I can add guide to our wiki with sample "user" creation that has full access to the cluster. Then add steps how to get this new user token and use it to log in. I hope this will help a bit.

**Comment by floreks** [comment]
@ronaldpetty We have updated our README and added guide to help new users log in to Dashboard.

https://github.com/kubernetes/dashboard/pull/2673
