### ISSUE TITLE
Error: 'tls: oversized record received with length 20527' Trying to reach: 'https://10.32.0.6:9090/

### ISSUE THREAD

**Issue by sachinar** [kubernetes/dashboard#2691]
Getting this error while running kube-dashboard

Error: 'tls: oversized record received with length 20527'
Trying to reach: 'https://10.32.0.6:9090/'
@kubernetes

**Comment by floreks** [comment]
https://github.com/kubernetes/dashboard/wiki/Accessing-dashboard

**Comment by mmikulicic** [comment]
The doc linked above says:

```
To access HTTPS endpoint of dashboard go to: http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/
```

I have kubectl proxy running in the background and I tried to open that link, and I can see this error:
```
Error: 'tls: oversized record received with length 20527'
Trying to reach: 'https://100.116.93.11:9090/'
```

This works though: http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy

**Comment by floreks** [comment]
You are using outdated version of Dashboard.

**Comment by jpavanaryan** [comment]
I had similar issue with URL, your link works @mmikulicic 
[http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy](http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy)

**Comment by dilumr** [comment]
@floreks thank you for suggesting a place to look at regarding the 'tls: oversized ...'.
I ran across the same problem while following the introductory steps in the book 'Kubernetes: Up and Running' (by Kelsey Hightower, Brendan Burns, and Joe Beda (O’Reilly). Copyright 2017 Kelsey Hightower, Brendan Burns, and Joe Beda, 978-1-491-93567-5.)

Building out the Kubernetes community is clearly a massive undertaking. 
In this case, I was reading a book, which suggested minikube as one possible alternative for getting started. 
Minikube itself is bringing together various pieces at different levels of abstraction.

I would very much appreciate any thoughts you have on how newcomers can (a) report issues, and (b) tackle the chicken and egg problem of getting started.
Specifically, I don't know how to update the version of Dashboard, nor adjust configuration yet.
Is the dashboard not a foundational part of Kubernetes? (If so, perhaps it should get introduced later in the book, and I'm happy to suggest that idea to the authors.)
If, on the other hand it *is* a foundational part, then is this something that needs a fix in minikube, because dashboard is far too old?
Or is minikube doing a reasonable job, and dashboard itself is too finicky about version mismatches?
Or is this a rare occurrence because of a bug in dashboard that has since been addressed?

Thanks again for the great work.

**Comment by tvildo** [comment]
In my case of minikube and kubernetes 1.9.0, I was accessing ui by going to 
http://localhost:8001/ui/
which redirects to:
http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/

Than I just replaced https:kubernetes with http:kubernetes in url so that final url looks like
http://localhost:8001/api/v1/namespaces/kube-system/services/http:kubernetes-dashboard:/proxy/

and after that it is working fine 👍

**Comment by floreks** [comment]
@dilumr 

> Is the dashboard not a foundational part of Kubernetes? (If so, perhaps it should get introduced later in the book, and I'm happy to suggest that idea to the authors.)

I think that Dashboard is considered by many people as the core UI of Kubernetes. It is not, however official UI in the full sense of that word. We are part of K8S org and we are working with the core, but this is still an open source project and its' existence depends very much on the community.

> If, on the other hand it is a foundational part, then is this something that needs a fix in minikube, because dashboard is far too old?

We are always trying to keep Dashboard up to date in popular external projects that are using it. Lately we are quite busy with different tasks and that is why it might be outdated in minikube. I think minikube team should also try to keep their cluster addons updated.

> Or is minikube doing a reasonable job, and dashboard itself is too finicky about version mismatches?

We are trying to be always up-to-date with latest releases of Kubernetes. There is a compatibility matrix available on our wiki pages that can tell you which versions of Dashboard will work with which versions of Kubernetes. Currently, there are no issues in this matter and latest Dashboard works correctly with K8S 1.8+.

>Or is this a rare occurrence because of a bug in dashboard that has since been addressed?

This particular error you've seen is not a bug but is caused by accessing Dashboard in a wrong way (http instead of https).

Personally, I think that users should first get to know how to provision the cluster (kubeadm, minikube, kubespray, etc.), then get familiar with kubectl a bit and then deploy and use applications like Dashboard. The key is to be able to correctly diagnose the issue. Very often people tend to think of Dashboard as a core component of Kubernetes without which cluster just does not work. Dashboard is just an application that is used to visualize and allow you to work with your cluster in a more user-friendly way.

**Comment by belgacea** [comment]
Thanks to @tvildo, I'm finally able to access the k8s dashboard from outside the cluster using : 
`kubectl proxy --address=IP --accept-hosts='.*'`
http://IP:8001/api/v1/namespaces/kube-system/services/http:kubernetes-dashboard:/proxy/
No auth was required. Is it a security issue or a expected feature ?

_Off-topic : My next goals are to expose the fabric8 console & other services. Do I need an Ingress controller or a nodeport is sufficient ? (Note : My k8s master runs on a virtual network interface. That's why I specified my ip to the proxy.)_

**Comment by y-manish** [comment]
This worked http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/#!/overview?namespace=default

**Comment by ddarilng85** [comment]
Thanks to all who participated in this thread!  Changing the "https:kubernetes-dashboard:/" to http worked for me also.

**Comment by TimZaman** [comment]
Meta: providing one-liners and just closing up issues is an ineffective way of dealing with users, you can tell by the sheer amount of votes. Good thing the community found solutions.

**Comment by willemodendaal** [comment]
Isn't there an easy way to query the api to figure out what the correct url is for my cluster? I spent fifteen minutes now googling and trying different random urls.

This one worked in the end: 
http://localhost:8001/api/v1/namespaces/kube-system/services/http:kubernetes-dashboard:/proxy/#!/overview?namespace=default

Note the http:kubernetes bit, not http**s**:kubernetes
