### ISSUE TITLE
Edit height is wrong in safari Version 10.1 (12603.1.30.0.34)

### ISSUE THREAD

**Issue by Bruce-sz** [kubernetes/dashboard#2749]
##### Steps to reproduce

env:
safari Version 10.1 (12603.1.30.0.34)
Edit height is wrong.

<img width="507" alt="qq20180110-083214 2x" src="https://user-images.githubusercontent.com/5813610/34750203-ce9f7160-f5e0-11e7-93c7-93663b2c367f.png">

##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.8.1
Commit: 7b3553aecf28224ef7275e157b5bba7dd23f436a
```

**Comment by floreks** [comment]
Should be fixed by https://github.com/kubernetes/dashboard/pull/2687. We have used a bit different library for editor and it was introduced in #2636. We'll try to do a `v1.8.2` release this week.
![image](https://user-images.githubusercontent.com/2285385/34762020-75468864-f5e6-11e7-9d75-f33f1f803891.png)
