### ISSUE TITLE
Mention that quick setup deployment requires the apiserver to reach pod IPs

### ISSUE THREAD

**Issue by nickray** [kubernetes/dashboard#2765]
##### Steps to reproduce
Deploy the dashboard via the README method on a cluster where the apiserver has no connectivity to pod IPs (e.g., myself following Kelsey Hightower's "the hard way" method on a home cluster). Try to access the dashboard using `kubectl proxy`.

##### Observed result
Timeout when browsing to `http://localhost:8001/ui`

##### Expected result
No timeout :)

##### Comments
I've seen a couple of closed issues on this here, and only diagnosed the problem by finding [this issue](https://github.com/kubernetes/kubernetes/issues/55238). From my understanding, the apiserver in general doesn't need to have network connectivity to the pods, and doesn't fall under the [k8s network model](https://kubernetes.io/docs/concepts/cluster-administration/networking/#kubernetes-model).

I suggest adding a remark to the NOTES in the "Getting Started" section of the README (along the lines of: in case of timeout, ensure that the apiserver has connectivity to pod IPs, for example by setting up the host server as a worker node).

**Comment by floreks** [comment]
I think that this is actually kubernetes responsibility to describe such details. Dashboard has nothing to do with incorrect cluster configuration. If apiserver service proxy throws timeout and application container shows status `Running` then user should first check cluster configuration. Pretty much any application that is capable of running inside the cluster would have to add such note because it can be accessed this way.

The easiest way to achieve pod communication is to deploy overlay network in the cluster and that is what most people do (flannel, weave). For new users it is also recommended to use some cluster provisioning tools as without proper knowledge about the kubernetes it is hard to pin down exact issue when encountering one.

Even this offical k8s docs page (https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-services/) does not mention in-cluster networking requirement for accessing services in the cluster.
