### ISSUE TITLE
edit a Secret should base64 decode the values then encode them on save

### ISSUE THREAD

**Issue by jstrachan** [kubernetes/dashboard#2782]
It would be really handy to be able to edit a Secret in the dashboard. Currently editing works, but it shows the base64 encoded values of the data map which means you have to mess around decoding/encoding base64 outside of the editor. It would be so much easier to just be able to edit them in the textarea directly ;)

**Comment by sachet-mittal** [comment]
Do we want to fix this?

I am asking because there is an explicit call of windows.atob in the secrets page.

refer: https://github.com/kubernetes/dashboard/search?utf8=%E2%9C%93&q=formatDataValue&type=

Correct me if I am wrong here.

**Comment by rakeshvanga** [comment]
I agree with jstrachan and this is a good to have feature.

**Comment by kasisnu** [comment]
This would be a useful feature. I'd like to work on it.

**Comment by floreks** [comment]
@kasisnu You are welcome to work on it.

**Comment by julienstroheker** [comment]
Hi @floreks @jstrachan 

I was looking at this, i'm new to this but willing to contribute :) 

Was curious what will be the best way to tackle this ?

SInce the edit component is generic for all kind of resources, i guess having an extra logic for secret here is not ideal : https://github.com/kubernetes/dashboard/blob/28f4c132308f3c83450e17a82760ef9cb2e930c8/src/app/frontend/common/dialogs/editresource/dialog.ts#L46

Another way could be to add an http interceptor on `get/secret` ?

I guess modifying the backend is no go ?

WDYT ?

**Comment by feloy** [comment]
I think the `stringData` field of SecretSpec would be useful for this feature. I'll have a try

**Comment by anshulahuja98** [comment]
> I think the `stringData` field of SecretSpec would be useful for this feature. I'll have a try

@feloy  Can you have a look at my PR for this issue and related issue #4255 ?

https://github.com/kubernetes/dashboard/pull/4290/files#diff-0ca22423fa7ae7f454e3081a82eafb18R124

![image](https://user-images.githubusercontent.com/36476228/66717178-aefa8400-edf3-11e9-8f96-bc48e83a19ed.png)

If we can perhaps finalize on what's to be done, I can modify my existing PR to reflect the required changes.

**Comment by greggbjensen** [comment]
I like that the Edit Secret modal shows everything as base64 encoded, since that matches the YAML file, and we probably want to still be able to copy and paste.

What I am working on instead is a quick edit, next to the eye icon of the secret page, that will allow you to open a modal for one entry, as text, in the secret and save.

![image](https://user-images.githubusercontent.com/1800213/77829836-2bef9080-70ea-11ea-9ddc-85d7116bfeac.png)

**Comment by ryanelian** [comment]
I'm going to throw in some inspirations for this issue.

[Openshift Console](https://github.com/openshift/console) (functions exactly like Kubernetes Dashboard) allows creating and editing Kubernetes secrets as if a key-value collection:

![image](https://user-images.githubusercontent.com/8892187/77830143-0a79bd80-7159-11ea-9c71-2794ad543d84.png)

![image](https://user-images.githubusercontent.com/8892187/77830158-28dfb900-7159-11ea-854b-18f2fb4cbe0f.png)

![image](https://user-images.githubusercontent.com/8892187/77830163-36953e80-7159-11ea-84e5-4a252d53c45a.png)

![image](https://user-images.githubusercontent.com/8892187/77830162-35fca800-7159-11ea-8e5d-0affb9800581.png)

![image](https://user-images.githubusercontent.com/8892187/77830182-62b0bf80-7159-11ea-9aea-58233e21768f.png)

**Comment by greggbjensen** [comment]
I put together this dialog for Quick Edit, just working on wiring it up to save.

![image](https://user-images.githubusercontent.com/1800213/77833311-11c1ac80-7102-11ea-8ff1-8d7a85d84162.png)

**Comment by greggbjensen** [comment]
This is complete and the pull request is ready:

**Added quick edit icon to Secrets page with dialog to decode and update a data value** #5039

**Comment by greggbjensen** [comment]
I re-implemented it as requested, with an inline edit.

**Implemented inline editing for data entries on Secrets page.** #5040

![image](https://user-images.githubusercontent.com/1800213/77841016-aa7c1a80-714a-11ea-9426-b7124e4ed387.png)

**Comment by maciaszczykm** [comment]
https://github.com/kubernetes/dashboard/pull/5040 covers that perfectly. You can edit the decoded value in the card and you can also edit the original value in the edit dialog.
