### ISSUE TITLE
user configurable browserNoActivityTimeout 

### ISSUE THREAD

**Issue by wu105** [kubernetes/dashboard#2815]
##### Environment

```
Dashboard version: 1.7.1
Kubernetes version: 1.8.4
Operating system: Oracle Linux 7.4
Node.js version: N/A
Go version: N/A
```

##### Steps to reproduce

Login to Web UI, sit 5 minutes, navigate on the Web UI
##### Observed result

the user is thrown to the login page. relogin does not get to the old page, e.g., select non default namespace
##### Expected result

- the timeout should be configurable at installation time.  
- login after a timeout should restore the old page, at least restore the selection of namespace.

**Comment by floreks** [comment]
Default session timeout is set to 15 min as specified here: https://github.com/kubernetes/dashboard/blob/master/src/app/backend/auth/api/types.go#L29

It is a configurable option already and can be changed by `token-ttl` argument as described here: https://github.com/kubernetes/dashboard/wiki/Dashboard-arguments

> login after a timeout should restore the old page, at least restore the selection of namespace.

It is normal behavior. After logout and login, you are normally redirected to some default page. In our case, it is overview page in a default namespace.

**Comment by mike818148** [comment]
@wu105 Yes, by default behavior, after the login it will always redirect to the Default Namespace. If you want to change the default namespace. You may need to modify the configure inside source and rebuild the image. 

In our case, we design simply let the login page to have a ?namespace= parameter to redirect to the desired namespace. In order to do so, we need to modify dashboard/src/app/frontend/common/namespace/module.js, and rebuild the whole docker image.
