### ISSUE TITLE
[RBAC] The namespace doesn't shown in the drop-down menu.

### ISSUE THREAD

**Issue by noskovao** [kubernetes/dashboard#2877]
##### Environment
```
Dashboard version: v1.8.3
Kubernetes version: v1.8.5
Operating system: Ubuntu 16.04.3 LTS
```

##### Steps to reproduce
1. Deploy k8s with RBAC
2. Deploy Dashboard
3. Create a service account
4. Create rolebinding for service account and clusterrole "admin"
5. Login to Dashboard using account's token.

##### Observed result
1. Falling by default in default namespace (unexpected). Getting permission errors (expected).
![image](https://user-images.githubusercontent.com/4687762/37022044-27f812d2-213b-11e8-9b60-fa3e53d7a534.png)
2. Clicking on drop-down menu to pick namespace where I have admin permission.
I do not see namespace(s) where I have admin access. (unexpected)
![image](https://user-images.githubusercontent.com/4687762/37022169-8e4ab03a-213b-11e8-8870-e604e3917354.png)
3. I need manually enter my namespace to get access to the objects.
![image](https://user-images.githubusercontent.com/4687762/37022218-b7f4dfdc-213b-11e8-9e64-8e4f03cdae9e.png)
4. After that I can see objects in namespace where I have admin access.
![image](https://user-images.githubusercontent.com/4687762/37022263-db3d523a-213b-11e8-8f68-09e6d32ac9a0.png)

##### Expected result
I expected to see namespace(s) where I have access.
Or getting redirected to namespace where I have access instead of default namespace.

##### Comments
Probably Dashboard we match token with namespace and redirect user(ServiceAccount) to proper namespace instead of entering namespace manually?
This is similar issue with #2738. As a temporally solution we may to provide ServiceAccount namespace list permission, but I guess SA shouldn't have access to list ALL namespaces.

**Comment by floreks** [comment]
Unfortunately, this scenario cannot be enhanced in a secure way. We would have to grant Dashboard SA permissions to LIST all namespaces by default in order to be able to check if logged in user has access to particular namespaces. This, however, can be a gateway to exploit cluster structure and possibly create some other security issues.

As a solution for this, we have introduced namespace selector that allows you to manually enter name of the namespace you want to get access to. This does not require LIST privileges and permissions can be more strict and user can only have access to chosen namespaces.

I think this works as expected and we can not enhance it easily without jeopardizing the security.

**Comment by floreks** [comment]
I am closing this, as mentioned expectations could introduce security issues and we can not implement it. We will only consider adding "default namespace" input option to local user settings so user would be always redirected to provided namespace instead of our default namespace `default`.
