### ISSUE TITLE
Documentation change request regarding basic authentication

### ISSUE THREAD

**Issue by tlopo** [kubernetes/dashboard#2916]
Following the documentation [here](https://github.com/kubernetes/dashboard/wiki/Access-control#basic)  it says that ABAC is required for basic auth to work. I've got basic auth working in our cluster using `--authorization-mode=Node,RBAC` and `--basic-auth-file=<path_to_file>`, no ABAC. 

I was about to configure ABAC, but decided to try without and it worked :)

**Comment by floreks** [comment]
There is also this part in the doc you have linked:

> In order to enable basic auth in Dashboard --authentication-mode=basic flag has to be provided. By default it is set to --authentication-mode=token.

**Comment by tlopo** [comment]
@floreks  that's still required, my point is that ABAC is not a requirement.

**Comment by floreks** [comment]
If I remember correctly there was an issue that without specifying additional flags, when passing incorrect credentials apiserver was falling back to anonymous user instead of throwing unauthorized error. Try to provide incorrect credentials and see if you will be able to log in using basic auth in Dashboard. It might have been fixed on K8S side.

**Comment by floreks** [comment]
Closing as there was no reply to my comment for a long time. We'll reopen if needed.
