### ISSUE TITLE
Kubeconfigs exceeding 4k do not work with the dashboard

### ISSUE THREAD

**Issue by drewwells** [kubernetes/dashboard#2981]
##### Environment

```
Dashboard version: Dashboard Version: v1.8.3 ec1d7de4456e6a397c7f931f0a2bfc74a6ca2e9c 
Kubernetes version: 1.8.11 dc60726484f6e327640ce43d2fb164b726dd3c3d
Operating system: Oracle Linux
Node.js version: n/a
Go version: 1.10
```

##### Steps to reproduce

Load the dashboard, I will use `kubectl proxy`
Navigate to http://localhost:8001
Click kubeconfig
Load kubeconfig that is larger than 4096 bytes

##### Observed result

No error given in the UI, opening the console shows the following error: 
`Cookie 'jweToken' possibly not set or overflowed because it was too large (4329 > 4096 bytes)!`
##### Expected result

Login successful, redirected to dashboard

##### Comments

As far as I have seen, there is no documentation mentioning this 4k limit here or in K8s itself. Documenting this limitation would be the more critical issue. As a new feature, the Dashboard should likely support any kubeconfig regardless of the current browsers cookie size limit.

**Comment by skattoju** [comment]
Issue persists for Kubernetes 1.10. We are using azure active directory to get a token. The login works if no LDAP groups are included in the token if they are, the token becomes too long and the above issue results.

Any updates ?

**Comment by trunet** [comment]
this is difficult problem to solve.

browser limits the cookie size to 4k. the token have to be somewhere because all the requests send the token. as the token is signed, you can't simply shrink or cut it.

the solution would be to save the token on local storage instead of a cookie, but local storage is not recommended to save a token.

**Comment by jecafarelli** [comment]
I hit this issue as well. The setup I have is:
dex/login app to generate the token
dashboard -> dex -> cluster for logging int with the id.

After decoding the JWT, it turned out the reason the token was so large was because I was in a bunch of ldap groups, and dex grabs them all and passes them. My workaround was to add an extra filter onto dex so that it only grab the groups I am interested in:

https://github.com/krishnapmv/k8s-ldap/blob/master/dex-cm.yml#L66

After adding this, the jwt was small enough for the browser to handle.

Im wondering if the real fix would be to make the jwt only have groups in it that are mentioned in bindings. That is, if this is also the reason other people are hitting this.

**Comment by skattoju** [comment]
Is there a reason local storage should not be used to store the token ? how is it less secure than a cookie ? Using azure active directory.. have not found a way to filter ldap groups...

**Comment by floreks** [comment]
I think we could by default use cookies, but add an option to use an alternative implementation that uses web/local storage to store token. From what I understand it is less secure and more vulnerable to i.e. XSS attacks. Probably we would add an argument to the backend plus add some switch to the settings page with information why is this option there.

This would be a part of the angular migration so don't expect this feature too soon. 😃

**Comment by skattoju3** [comment]
One work around is to the a desktop client to access the dashboard instead of going through a browser ex: https://kubernetic.com/

/close

**Comment by jnovick** [comment]
Any solution to this yet?

**Comment by floreks** [comment]
Not really. Using local storage is not considered secure. Either pass the token only or use some reverse proxy with IdP to inject authorization header to every request to Dashboard. This way the login view will be skipped.

**Comment by SayakMukhopadhyay** [comment]
> Either pass the token...

I am facing the same issue and I am passing the token directly in the login screen. But Azure AD tokens seems to be large enough to make the JWE token to exceed 4k (its 4303 bytes for me) and hence I am unable to login via the token issue by Azure AD. I have came here as #3081 is closed as duplicate.

Knowing the restrictions, using a reverse proxy to inject the headers before it hits the dashboard seems like the only way out.
