### ISSUE TITLE
Move wiki into docs following traditional k/ repos

### ISSUE THREAD

**Issue by jimangel** [kubernetes/dashboard#3172]
I'm opening an Issue to track the docs overhaul. I'll be submitting a PR shortly to bring all of the wiki into a docs folder as a first step. I've also fixed any links I found referencing the wiki.

TO DO:
- [ ]  after merged PR, have a repo owner [delete the wiki](https://stackoverflow.com/questions/39176623/how-to-delete-githubs-wiki-homepage/42653762)
- [ ]  create roadmap with ng2 migration plan
- [ ]  update compatibility matrix
- [ ]  clearly state plans to support 3 most current releases of k8s (and delete reference to older versions)
- [ ]  clean up main README.md install instructions (take content from /docs)
- [ ]  create more focus and organization around docs and categories (contrib / user / install / adv)

**Comment by floreks** [comment]
We have actually moved recently our whole documentation from the repo/docs to the wiki pages as we have found it to be more clean and easier to manage, and navigate. Why should we go back to the old approach? I am not sure if this is a good idea. @maciaszczykm what do you think?

**Comment by jeefy** [comment]
Mirroring @jimangel's comment. 

In an effort to be consistent with the main k/* repos, documentation should be moved back into the repo. We discussed at last week's UI call and it was received favorably.

I think the burden of managing docs in the repo shouldn't be bad now that UI has more effort behind it and people eager to contribute. 

Another thought: Once docs get merged back into the repo, we could also ask sig-docs to give it a once over and see if there is any glaringly obvious standard thing we're missing. :)

**Comment by floreks** [comment]
Standardization would be good if we would consider documentation for similar software and if actually, all repos would follow the same pattern. In case of K8S core pretty much whole documentation is hosted outside of the core repository and is accessible on a separate page. Also, documentation for the webapp will look different than deployment software like, i.e. kubeadm, kops.

Few of the main reasons, we decided to move documentation to the wiki pages was that:
1. As developers, we have the best knowledge about how Dashboard works and how to describe it.
2. Wiki pages give us an easy way to navigate through the whole documentation using the nav panel. At all times the user knows where he is and can easily jump to other unrelated topics. 
3. ~90% of external contributions (PRs) related to docs were only fixing misspells, not actually improving the documentation quality.
4. Writing and editing documentation on wiki pages is much faster and it does not require from us creating PRs.

Due to mentioned things and few others I am not sure if sacrificing readability, easier navigation, time-saving during editing, etc. just for the sake of "standarization" is good.

There is also an option to open wiki to external contributors, but then we would need someone to oversee the docs on daily basis to make sure that it was not changed by someone unauthorized.

**Comment by jimangel** [comment]
Beyond standardization, I think there are more benefits over the wiki. Addressing your comments:

> 1. As developers, we have the best knowledge about how Dashboard works and how to describe it.

Moot point, as developers, you can still guide the markdown files as you see fit from wiki or /docs

> 2. Wiki pages give us an easy way to navigate through the whole documentation using the nav panel. At all times the user knows where he is and can easily jump to other unrelated topics.

As a dashboard user, I've never found the nav panel to be a deal breaker. I am usually searching out a specific top or coming to a specific page from a search.

> 3. ~90% of external contributions (PRs) related to docs were only fixing misspells, not actually improving the documentation quality.

This is what we're trying to change, open it up more to the community to easily allow more feedback / changes. Considering there is a major migration underway, making this project easy to contribute to should be a top priority. It seems like k/dashboard has really slowed down in development over the past few releases and there's an active effort to bring it back to life.

> 4. Writing and editing documentation on wiki pages is much faster and it does not require from us creating PRs.

I believe this is focused on keeping the docs closed for the original maintainers and goes against my response to 3. It might be easier for you, but not the greater community. Going the traditional /docs route would also solve the last comment about opening up the wiki.

It appears that you don't see value in this and I'm trying to understand. If the general consensus in k/dashboard is to continue using the wiki, I'm ok with that! I'm trying to understand where you're coming from too.

**Comment by floreks** [comment]
> Moot point, as developers, you can still guide the markdown files as you see fit from wiki or /docs

This one is actually connected with 4th point. We were able to save much time while creating documentation because we didn't have to create PR for every change and we were anyway the only ones creating docs.

> As a dashboard user, I've never found the nav panel to be a deal breaker. I am usually searching out a specific top or coming to a specific page from a search.

For me navigating over the docs stored on repo whether it was Dashboard, kubeadm or other repository was always counterintuitive. I could never quickly find what I was looking for just by starting from the main docs page.

> This is what we're trying to change, open it up more to the community to easily allow more feedback / changes. Considering there is a major migration underway, making this project easy to contribute to should be a top priority. 

The project is still easy to contribute to, isn't it? Documentation is only a small part of it and decision to not keep it directly on the repo does not close the project for the contributors. Overall, most of the PRs are and always were related to the codebase rather than documentation itself.

> It seems like k/dashboard has really slowed down in development over the past few releases and there's an active effort to bring it back to life.

After me and @maciaszczykm have been moved to another project, Dashboard development was pretty much on hold. We have tried to find someone to take over but no one had enough time to work on it full time as we did. Right now we are trying to push it further once again and it is awesome that there are more people willing to contribute.

> I believe this is focused on keeping the docs closed for the original maintainers and goes against my response to 3. It might be easier for you, but not the greater community. Going the traditional /docs route would also solve the last comment about opening up the wiki.

I understand why it might seem to be a good idea to move it back to docs, however try to understand my point. I have been working on this project from the beginning and most of this time documentation was stored on the repo. All this time, even though it was open for contributors, 99% of it was created and redacted by the dashboard maintainers team. From time to time someone from the outside updated outdated link.

I guess my concern is if external contributors can actually provide technical documentation for the Dashboard to improve it (new features, releases, usage changes) or will it be mostly (as before) redacting existing docs and fixing misspells?

**Comment by jimangel** [comment]
Good points worth considering. Will you and @maciaszczykm be able to attend the sig-ui meeting today? Maybe we can chat and get a general consensus?

> I guess my concern is if external contributors can actually provide technical documentation for the Dashboard to improve it (new features, releases, usage changes) or will it be mostly (as before) redacting existing docs and fixing misspells?

I think I can help here (and this isn't a /docs vs wiki)... I believe that if documentation is clearly laid out to help developers and encourage community participation, we'll see more technical PRs for docs and the number of contributors grow. This will take some time to clean up the docs, update the contributing guides, updating the user guides etc.

I do understand now, if it's just you and @maciaszczykm how using wiki would be easier for rapid development but I think switching to /docs and an active effort to clean up docs will encourage growth and adoption in k/dashboard. I also think Kubernetes itself is growing rapidly and we're seeing more contributors pitching in (vs. the early days of the k/dashboard).

There's only one way to find out :)

**Comment by maciaszczykm** [comment]
Hi @jimangel, nice to meet you. In general I agree with @floreks as I believe that current way of storing docs is working fine. Back in the past we were keeping all docs in `/docs` directory, but nobody was paying much attention to it. There were not many contributions besides typo fixes (it was almost always outdated) and users were not reading it before posting new issues. We have decided to change that, keep them up to date and make them more accessible.

**Comment by jimangel** [comment]
@maciaszczykm, nice to meet you too! It's kind of funny, I saw this as an opportunity to clean up the docs before the migration - as you said - a lot will be changing. I'm reading and learning the code but I'm not at a point to contribute to the migration, so I figured I could help out with preparing the docs.

@floreks I'm open to that suggestion of allowing external contributions to the wiki, but it appears there is a strong feeling on the direction / purpose of the docs. Are you ok with me making changes to clean it up?

**Comment by maciaszczykm** [comment]
@jimangel By opening Wikis for external contributors I believe we are solving one of the problems that you have mentioned. Let's see if it goes in right direction and reconsider before migration finish, we will need to update docs anyways.

As it seems to be introduction to the project for you I would reconsider if it is reasonable to work on current docs or if you should focus on docs for new version (Angular migration). Wouldn't it be better for you and the project?

**Comment by jimangel** [comment]
Closing per discussion about opening up wiki, will update readme and wiki moving forward.
/close
