### ISSUE TITLE
Error when opening Pod shell in Firefox Developer Edition

### ISSUE THREAD

**Issue by vzaytsev** [kubernetes/dashboard#3345]
##### Steps to reproduce

Login to dashboard, select namespace, select a Pod wich we can exec command (can open terminal)

Press "Exec" button

##### Environment
```
Installation method: Kops
Kubernetes version: 1.9.10
Dashboard version: v1.8.3
Commit: ec1d7de4456e6a397c7f931f0a2bfc74a6ca2e9c
OS: macOS 10.14.1
Browser: Firefox Developer Edition 64.0b9 (64-bit)
```

##### Observed result
Browser is opening new window, but load inside Pod page instead of Shell

##### Comments

Screenshot https://yadi.sk/i/dPHHWxwPbht4Ng

Safari, Chrome works fine

**Comment by maciaszczykm** [comment]
@vzaytsev Thank you for reporting the issue, but we will not fix it on our own. We cannot maintain browser compatibility for "developer edition" or old browsers. This is probably not even possible to fix on our side because most probably the issue is on the terminal module or browser side.

/triage unresolved
/close
