### ISSUE TITLE
Dashboard reported Internal Server Error (500):

### ISSUE THREAD

**Issue by JamesHollinger2** [kubernetes/dashboard#3364]
##### Environment
```
Installation method: 
Kubernetes version:
Dashboard version: v1.10.0
Commit: aa1b6c0c31c4b3b703e16e554a15ed2a019aad47
```

##### Observed result
Dashboard reported Internal Server Error (500):
```
square/go-jose: error in cryptographic primitive

```

**Comment by jeefy** [comment]
This usually happens when you've previously connected to a Dashboard instance, then recreated it. The cookies are stale, from the old instance.

If you wait long enough, or pop open an Incognito tab, it should work. :)

While there's room for improvement with this, this is a known behavior and not a bug. If the above info doesn't help, please re-open the ticket with more info. Thanks!

/close
