### ISSUE TITLE
Dead Keys - OSX qwertz keyboard

### ISSUE THREAD

**Issue by hjanuschka** [kubernetes/dashboard#3759]
latest dashboard version.

i am having problems with some keys using my german keyboard on OSX - when in `exec` of a pod/Container

like `|`  - it requires me to press `OPTION+7`  which produces a `bell`  and does not output the character same goes for: `{`  which is `OPTION+8`

is there any known issue about that?

**Comment by floreks** [comment]
Check if it works in this demo: https://xtermjs.org/

If not then this is a xterm issue.

**Comment by hjanuschka** [comment]
gr8! yep seems to be an issue with xtermjs, going to report it there, thx!

**Comment by floreks** [comment]
@hjanuschka Actually that was my bad. Dashboard `v1.10.X` uses `hterm`.

https://hterm.org/?term-version=1.00

But if it doesn't work for both `hterm` and `xterm` then they have to fix that.

**Comment by hjanuschka** [comment]
broken on hterm too, opening issues on both repo's :D

**Comment by floreks** [comment]
Greenekeeper is keeping our deps updated so once it will be fixed there, it will get into Dashboard.

**Comment by mofux** [comment]
Hi, it's Thomas from the xterm.js team. We think this issue is caused by the docker container using a different locale to the client OS running the dashboard. I think the problem could be solved by passing a custom `LANG` environment variable to the docker exec command (in the example below, using de_DE as the LANG variable):

```javascript
{
  // ... Docker exec options ...,
  Env: [
    "LANG=de_DE.UTF-8"
  ]
}
```

This is only a guess, but I'm 99% sure that the problem is not with `xterm.js` nor `hterm`, but with the host environment itself.

**Comment by hjanuschka** [comment]
just for the record - env does not fix it
![Bildschirmfoto 2019-04-30 um 17 20 58](https://user-images.githubusercontent.com/2891702/56973127-8562de80-6b6c-11e9-8f4d-2451fc820f2b.png)


but i am fine with closing it , going to use `attach` instead of web terminal.

**Comment by mofux** [comment]
Just another thought, if you compare the output of the `locale` and `env` commands between the kubernetes dashboard and a regular `attach` session, can you see any differences?
