### ISSUE TITLE
Im getting this error can you help me

### ISSUE THREAD

**Issue by GMKBabu** [kubernetes/dashboard#3804]
Your connection is not private
Attackers might be trying to steal your information from 13.126.203.219 (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_INVALID
 
Help improve Safe Browsing by sending some system information and page content to Google. Privacy policy
13.126.203.219 normally uses encryption to protect your information. When Google Chrome tried to connect to 13.126.203.219 this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be 13.126.203.219, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.

You cannot visit 13.126.203.219 right now because the website sent scrambled credentials that Google Chrome cannot process. Network errors and attacks are usually temporary, so this page will probably work later.

**Comment by tony-liuliu** [comment]
Generate self-signed certificates
[root@es-master-1 ~]# mkdir certs
[root@es-master-1 ~]# openssl req -nodes -newkey rsa:2048 -keyout certs/dashboard.key -out certs/dashboard.csr -subj "/C=/ST=/L=/O=/OU=/CN=kubernetes-dashboard"
[root@es-master-1 ~]# openssl x509 -req -sha256 -days 365 -in certs/dashboard.csr -signkey certs/dashboard.key -out certs/dashboard.crt

Generate the kubernetes-dashboard-certs certificate file
[root@es-master-1 ~]# kubectl create secret generic kubernetes-dashboard-certs --from-file=certs -n kube-system

Make sure the kubernetes- dashboards -certs secret has been imported correctly
[root@es-master-1 ~]# kubectl -n kube-system describe secret/kubernetes-dashboard-certs

Try dashboard again

**Comment by floreks** [comment]
@GMKBabu provide your own certificates as described by @tony-liuliu  if self-signed ones are not allowed by your browser configuration.

/close

**Comment by ArvinSiChuan** [comment]
I fixed this by using the v1.10 version instead of v2.0 beta

**Comment by zimmertr** [comment]
@ArvinSiChuan & other

FYI for those using v2 of the dashboard you will need to change the namespace in which you create the `kubernetes-dashboard-certs` secret as it has been moved to `kubernetes-dashboard` from `kube-system`.

**Comment by rombie** [comment]
Hi, can some one please help? I am unable to use dashboard with chrome any more..., after I moved to https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta5/aio/deploy/recommended.yaml

**Comment by halsafar** [comment]
@rombie Same problem.  Chrome refuses the dashboard entirely due to "scrambled credentials".  Firefox allows it but claims the certificate is from 2001.

Every instruction set to provide my own certificate is not working.

**Comment by zehuaiWANG** [comment]
@halsafar provide your own certificates as described by @tony-liuliu if self-signed ones are not allowed by your browser configuration. （by the way，adding "--test-type --ignore-certificate-errors" to chrome's quick start command may also work. This depends on your chrome version.）

**Comment by sondnpt00343** [comment]
I solved it. The problem here is that the automatically generated certificate does not work in many browsers. I have solved and created a story here:
https://medium.com/@sondnpt00343/deploying-a-publicly-accessible-kubernetes-dashboard-v2-0-0-betax-8e39680d4067

**Comment by zimmertr** [comment]
Here is some Ansible code to do the same thing:

https://github.com/zimmertr/Bootstrap-Kubernetes-with-QEMU/blob/master/playbooks/optional/deploy_dashboard.yml

**Comment by graywen24** [comment]
just have a update here.. as i  am using v2.0 so encountered same issue.
 
since v2  secret as it has been moved to  namespace "kubernetes-dashboard" from kube-system.
so here is how I solve the issue.
before apply the yaml file
`$ openssl req -nodes -newkey rsa:2048 -keyout certs/dashboard.key -out certs/dashboard.csr -subj "/C=/ST=/L=/O=/OU=/CN=kubernetes-dashboard"`
`$ openssl x509 -req -sha256 -days 365 -in certs/dashboard.csr -signkey certs/dashboard.key -out certs/dashboard.crt`

create the namespace first
`$ kubectl create namespace kubernetes-dashboard`
then create the screct
`$ kubectl create secret generic kubernetes-dashboard-certs --from-file=certs -n kubernetes-dashboard`
then apply the yaml file, even it will show error secret and namespace exist 
`$ kubectl create -f kubernetes-dashboard.yaml
serviceaccount/kubernetes-dashboard created
service/kubernetes-dashboard created
secret/kubernetes-dashboard-csrf created
secret/kubernetes-dashboard-key-holder created
configmap/kubernetes-dashboard-settings created
role.rbac.authorization.k8s.io/kubernetes-dashboard created
clusterrole.rbac.authorization.k8s.io/kubernetes-dashboard created
rolebinding.rbac.authorization.k8s.io/kubernetes-dashboard created
clusterrolebinding.rbac.authorization.k8s.io/kubernetes-dashboard created
deployment.apps/kubernetes-dashboard created
service/dashboard-metrics-scraper created
deployment.apps/dashboard-metrics-scraper created
Error from server (AlreadyExists): error when creating "kubernetes-dashboard.yaml": namespaces "kubernetes-dashboard" already exists
Error from server (AlreadyExists): error when creating "kubernetes-dashboard.yaml": secrets "kubernetes-dashboard-certs" already exists`


after that  you will be able to access the dashboard by pass the chrome error.

**Comment by mycvvn** [comment]
@graywen24 I solved it. You can see...
https://github.com/kubernetes/dashboard/issues/3804#issuecomment-553968120

**Comment by gladmo** [comment]
chrome://flags/#allow-insecure-localhost

**Comment by c0h1b4** [comment]
> https://medium.com/@sondnpt00343/deploying-a-publicly-accessible-kubernetes-dashboard-v2-0-0-betax-8e39680d4067

**Not working.** 

After following your instructions:

> 
> Your connection is not private
> 
> Attackers might be trying to steal your information from 192.168.xxx.xxx (for example, passwords, messages, or credit cards). Learn more
> NET::ERR_CERT_INVALID
> ...
> You cannot visit 192.168.xxx.yyy right now because the website sent scrambled credentials that Google Chrome cannot process. Network errors and attacks are usually temporary, so this page will probably work later.

**Comment by zimmertr** [comment]
Generate a new certificate. See how here:

https://github.com/zimmertr/Bootstrap-Kubernetes-with-QEMU/blob/master/playbooks/optional/deploy_dashboard.yml
