### ISSUE TITLE
Reenable namespace change dialog

### ISSUE THREAD

**Issue by maciaszczykm** [kubernetes/dashboard#3909]
At the moment its code is commended in the `NamespaceSelectorComponent`.

**Comment by abursavich** [comment]
That dialog is ***so annoying***. If you're going to reenable it, can you also add an option to disable it (similar to page size, maybe)?

**Comment by maciaszczykm** [comment]
Good point, I think we can start some discussion here if we need that.

**Comment by floreks** [comment]
@abursavich The dialog is needed for some users as it informs you about "silent" namespace change. You might not even realize in some cases that namespace has been changed. This creates confusion. We could maybe add a checkbox to the dialog, to remember user choice and not display it over again.

**Comment by abursavich** [comment]
Hitting the problem again and taking a minute to analyze it, I think my biggest problem is the wording and that YES/NO are inverted from what I expect.

When trying to change from namespace _foo_ to _bar_, you're asked if you want to **Change namespace?** but you have to read the fine print because selecting **YES** switches you backwards to _foo_ not forwards to _bar_.

---
**Change namespace?**

Selected resource is in a different namespace than currently selected.
Do you want to change namespace from _bar_ to _foo_?

. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . [ **YES** ] . . . . . .  [ **NO** ]


---

I always hit **YES** when I want to change namespace and **NO** when I don't want to change namespace.

**Comment by floreks** [comment]
Actually in the new version wording have been updated. Is it now:

----
#### Namespace conflict

Selected namespace is different than namespace of currently selected resource.
Do you want to stay on current page and change namespace from <i>foo</i> to <i>bar</i>?

_YES_         _NO_ 

----
