### ISSUE TITLE
Dashboard changed after reinstall

### ISSUE THREAD

**Issue by ajouve** [kubernetes/dashboard#4038]
##### Environment

```
Installation method: Kops
Kubernetes version: v1.11.7 / v1.11.6
Dashboard version: v2.0.0-beta1+0.gfb8fc184
Operating system: Ubuntu
```

##### Observed result

Five month ago I installed the dashboard and I had exact same dashboard as this one https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/

Few days ago, I had an issue telling me the dashboard was not installed so I ran `kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta1/aio/deploy/recommended.yaml
`

And new I have another dashboard with bugs (see image attached)

![Screen Shot 2019-07-10 at 16 02 02](https://user-images.githubusercontent.com/2337492/60976353-ce35d100-a32d-11e9-8cc5-313fc0745ab6.png)

I do not know if this is related but I have a lot of error `40774 log.go:172] http: proxy error: context canceled` on my `kubectl proxy`

Thanks

**Comment by floreks** [comment]
As you can see in the link _...dashboard/**v2.0.0-beta1**/aio..._, it is a first beta release. If you want something stable then you can use https://github.com/kubernetes/dashboard/releases/tag/v1.10.1

Regarding the issue itself, I do not see any "bugs" on the screenshot and this kind of `kubectl proxy` errors are not caused by deployed applications, so this is not a Dashboard issue. 

If you are referring to the empty metrics then as stated in the [release notes](https://github.com/kubernetes/dashboard/releases), Dashboard now supports `metrics-server` thus requires it to gather metrics.

**Comment by ajouve** [comment]
Thanks @floreks, should them the doc link to install a stable version ?

```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta1/aio/deploy/recommended.yaml
```

**Comment by floreks** [comment]
We have updated it to refer the latest beta as people were waiting for it a long time. There should be no issues for people already using `v1.10.1`. All information is available on this repo.

**Comment by floreks** [comment]
We have updated it to refer the latest beta as people were waiting for it a long time. There should be no issues for people already using `v1.10.1`. All information is available on this repo.

/close
