### ISSUE TITLE
Follow v2 module documentation

### ISSUE THREAD

**Issue by bouk** [kubernetes/dashboard#4110]
Hi, I just want to give you a heads-up that you might need to follow the [modules documentation](https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher) around releasing a v2, to ensure it’s fully compatible with the mod tool. I believe all you will need to do is append `/v2` to the `module` statement in `go.mod`.

**Comment by maciaszczykm** [comment]
I have taken a look into this and I think we don't need to do it, at least for now. Dashboard is our product and we are releasing it as a whole package. Frontend modules, backend modules - everything is part of the dashboard.  If there is a good reason for having this then let's reopen it, otherwise, I will close it as it complicates things.

> I just want to give you a heads-up that you might need to follow the modules documentation around releasing a v2

During the migration, the backend has not changed that much. Changes related to adding Go modules were done separately.

> I believe all you will need to do is append /v2 to the module statement in go.mod.

That's only the first step as later we need to change all imports in our app to use `/v2`. Then our build pipeline is pretty complex and these changes needs to be applied too. I'd like to avoid it if we can.
