### ISSUE TITLE
Unclear message if service exists

### ISSUE THREAD

**Issue by cheld** [kubernetes/dashboard#432]
#### Issue details
Validation message might be confusing

##### Steps to reproduce
Steps:
1. Open deploy from settings
2. Enter test as app name
3. Deploy
4. Delete test, but not service
5. Open deploy again
6. Enter test as app name

##### Observed result

Validation error: "Application with this name already exists within namespace default."

However, Zerostate page is shown. So cluster seems to be empty.

##### Expected result
Unclear, at least message must be improved and documentation

**Comment by bryk** [comment]
Fix should be easy. We can do this for 1.0. What do you think?

**Comment by maciaszczykm** [comment]
Working on it.

**Comment by maciaszczykm** [comment]
I'm thinking about solution for this. The most accurate one seems to be sending more information from backend (at the moment it's whole validation result, for replication controller and service name together). Instead of it we could send both of these information. However, it will require more changes in architecture to display correct message in UI depending on data from backend. I'm not sure if we should complicate it like this.

Second solution is really simple and it's changing validation message. How it should look like? Now it's `Application with this name already exists within namespace ?`. My proposition is `Replication controller or service with this name already exists within namespace ?`. What do you think about it? Do you have any other propositions?

**Comment by bryk** [comment]
The latter sounds good enough :) Can you send a PR? :)

**Comment by maciaszczykm** [comment]
@bryk Sure.
