### ISSUE TITLE
Why does dashborad not support multi-cluster management?

### ISSUE THREAD

**Issue by zehuaiWANG** [kubernetes/dashboard#4405]
##### What would you like to be added

multi-cluster management like rancher

##### Why is this needed
This feature is very important for multi-cluster management. In order to prevent risks, current applications are generally deployed in multiple clusters. Open source software like rancher supports multi-cluster management. Why does dashborad not support multi-cluster management?

##### Comments

@floreks @maciaszczykm @bryk I think this feature is very important. Do we consider implementing it later? Thank you all.

**Comment by floreks** [comment]
Considering current architecture, supporting multiple clusters by the single Dashboard instance would be a very big task. It was always destined to monitor a single cluster it is installed in. Basically, you deploy it in every cluster you want to monitor.

There already is an issue for that (#582), but it always had a very low priority, because it can be solved by using multiple instances of Dashboard.

/duplicate 
/close

**Comment by zehuaiWANG** [comment]
@floreks thank you, floreks, I wonder if I complete the multi-cluster expansion of the dashboard, will it be accepted by the dashboard?

**Comment by zehuaiWANG** [comment]
@maciaszczykm

**Comment by maciaszczykm** [comment]
@zehuaiWANG Yes, of course. But it has to be done in a good way. Having no impact on a current setup etc.
