### ISSUE TITLE
I would like to be able to change the time zone

### ISSUE THREAD

**Issue by pog2g** [kubernetes/dashboard#4685]
Changing the time zone is a very necessary function, I hope you can provide, or give a way to change. Or can use PodPreset

**Comment by floreks** [comment]
All times displayed in Dashboard are always adjusted to your local timezone presented by the browser. It's done this way to avoid complicated time diff calculations as we have to properly sync time between server and browser, because all dates we get from server are based on its' own time zone and server can be located in a different time zone. You are welcome to contribute such feature, but for us it would be at the end of our backlog. I don't see any advantages of adding that.

**Comment by zehuaiWANG** [comment]
@floreks I agree. I think we can close this issue now.

**Comment by floreks** [comment]
@pog2g you can propose such feature in a PR, but we will not add that as explained in my previous comment.

/close
