### ISSUE TITLE
Cpu & Memory graphs - strange curve shape

### ISSUE THREAD

**Issue by grunlab** [kubernetes/dashboard#4818]
Deployed version: 2.0.0 rc2
Browser: Firefox 72.0.1

Cpu & Memory graphs --> the shape of the curve is a bit strange

![Capture d’écran_2020-01-23_19-12-04](https://user-images.githubusercontent.com/33118366/73011322-48cec580-3e14-11ea-9837-9eb227e503ef.png)

**Comment by leeblee** [comment]
good

**Comment by floreks** [comment]
Ye, the approximation function used to draw graphs seems not to work with quick usage spikes. We have to change it to a different one.

**Comment by grunlab** [comment]
Additional info:
I'm using metrics-scraper:v1.0.2 with the following custom setting : --metric-resolution=10s
Without the custom metric resolution (default = 1min), the graphs are OK:

![Capture d’écran_2020-01-27_22-26-44](https://user-images.githubusercontent.com/33118366/73215315-23afbf00-4154-11ea-8de4-ffe491a97412.png)

**Comment by floreks** [comment]
Ye, that's understandable as longer time interval is not that susceptible to usage spikes. I am afraid it might be hard to find good approximation that looks like and works in all cases.

**Comment by floreks** [comment]
Ye, that's understandable as longer time interval is not that susceptible to usage spikes. I am afraid it might be hard to find good approximation that looks like and works in all cases.

**Comment by grunlab** [comment]
For my understanding : Why doing approximation? Just to get smooth curve hiding the spikes?
Why not just displaying "raw" data from the metrics-scrapper?

**Comment by floreks** [comment]
It's the external library that requires it. Approximation is used as you only get data points, and you have to draw the lines somehow.

**Comment by grunlab** [comment]
Humm ... ok, so the used external library is not able to simply links the data points with lines instead of approximated curves ... right ?
For the small graphs, data points looks to be linked with lines and the resulting curve shape is not so bad/ugly  ;-)
So maybe the metric resolution should be used somehow as a parameter of the approximation? (certainly simple to say but not to solve :-))
Nevertheless, this topic is not urgent at all and i would like to congratulate kubernetes-dashboard team for all the accomplished work ... it looks really promissing !

**Comment by floreks** [comment]
@grunlab http://bl.ocks.org/d3indepth/raw/b6d4845973089bc1012dec1674d3aff8/

Here is curve explorer. Currently we are using `curveBasis`. There is simple linear curve also, but I guess `curveMonotoneX` looks a bit nicer and does not seem to be affected by usage spikes.

**Comment by floreks** [comment]
@grunlab After investigating in detail scraper and dashboard I do understand why you were getting such strange graph shape. 

The X axis on the graphs shows only time in minutes. Since you have decreased metric time resolution interval, scraper was returning multiple metrics for the same minute. As we were still able to provide multiple data points with different Y, but same X to generate the graph, it tried to show usage changes that occurred during this additional time period and ended up showing weird spikes, because X, in reality, did not change.

To sum up, Dashboard does not support changing time resolution for the scraper to values lower than 1 minute as it only shows date on the X-axis in "%H:%M" format. We do not want to add seconds to that as it could end up generating hundreds of points and everything would become unreadable. We would need to allow configuring time frame and data format for graphs in the Dashboard also if we would want to support that. 

I do not consider this one a bug then, change metric resolution time to 1m or more. We can think about adding a feature to better support smaller time frames in the future.

/close

**Comment by grunlab** [comment]
@floreks Ok ... fyi, i've opened a new "kind/request" issue (https://github.com/kubernetes/dashboard/issues/4844)
