### ISSUE TITLE
Show current pod count in edit dialog

### ISSUE THREAD

**Issue by cheld** [kubernetes/dashboard#482]
#### Issue details
The current pod count is not shown in the edit dialog.

##### Environment

Browser: Chrome

##### Steps to reproduce
1. Deploy app
2. Go to details
3. Press edit 
3. Scale up to 5 pods, press ok
=> now scale up by one pod
4. Press edit
5. Press up button next to input field

##### Observed result
1 is shown in input field

##### Expected result
6 is shown

**Comment by floreks** [comment]
We've already discussed that with @bryk when this was implemented and decided to show information about current status of pods in the above description because putting some arbitrary number directly in input field might be misleading for users. This would require at least adding some tooltip with some explanation why 1,6,52,5123 is shown when dialog is open. Number itself doesn't provide any useful information.

Clicking up when input field is empty and expecting to get current number of pods + 1 is also very confusing, because user doesn't know where this number came from. Is it error? Random number?

@bryk what do you think?

**Comment by bryk** [comment]
To me we should make the input empty and just show in plain text current state. Resising RC is not that trivial operation, so requiring user to type the input is at least a small safeguard.

**Comment by cheld** [comment]
Ok, if it is intentional than we should keep it.
