### ISSUE TITLE
sign in kubernetes dashboard with username and password

### ISSUE THREAD

**Issue by ManivelRR** [kubernetes/dashboard#4951]
Hi Team,

I like to sign in the kubernetes dashboard with username and password instead of below token method.

Is this possible ? If yes,please advise with the steps

![image](https://user-images.githubusercontent.com/49863883/75369296-33ecc280-58e9-11ea-8330-58245a57c3ad.png)

Thanks in advance.
Manivel R

**Comment by floreks** [comment]
In order to be able to use basic auth in Dashboard, first, you need to configure Kubernetes to allow basic auth and accept username/password.

https://kubernetes.io/docs/reference/access-authn-authz/authentication/

When you make sure that you are able to i.e. use `kubectl` configured with username/password to access the cluster, you can enable basic auth in Dashboard. See [arguments](https://github.com/kubernetes/dashboard/blob/master/docs/common/dashboard-arguments.md) doc and look for `authentication-mode` flag.

It is also shortly described in [user documentation](https://github.com/kubernetes/dashboard/tree/master/docs/user/access-control#basic).

**Comment by tufuuuu** [comment]
When I add --basic-auth-file in my kube-apiserver.yaml, the apiserver in docker is "pause", and I cant use kubectl to command, is there any other parameter i have to add

**Comment by floreks** [comment]
We do not provide support for Kubernetes core here. If you're having issues with configuring your cluster ask on stackoverflow or kubernetes core repo. As I have provided information about how to configure Kubernetes Dashboard and answered the initial question, I'll close this.

/close
