### ISSUE TITLE
Setting a minimal "Max Y axis" for (CPU) graphs.

### ISSUE THREAD

**Issue by nielsbasjes** [kubernetes/dashboard#4995]
##### What would you like to be added
I propose that the metrics graph gets some constraints on the min/max of the Y axis.

For the CPU graph I propose to have a 'smallest' range from 0 to 0.1

##### Why is this needed
In a namespace with very low load the graphs are misleading and give the impression of huge fluctuations when almost nothing happens.

Using v2.0.0-rc5 I see this in a namespace with no load.
![image](https://user-images.githubusercontent.com/240096/76403828-caa78d80-6385-11ea-91af-435bf5c1cb31.png)

When there is very little load I see this:
![image](https://user-images.githubusercontent.com/240096/76403922-ef036a00-6385-11ea-9f29-0cefc946e6b6.png)

and a few minutes later
![image](https://user-images.githubusercontent.com/240096/76404451-c891fe80-6386-11ea-8dc0-9648bb78bc95.png)

![image](https://user-images.githubusercontent.com/240096/76406886-ccc01b00-638a-11ea-86a2-da666a204a54.png)

##### Comments
I think the Y axis minimum must be fixed on 0 and the lowest possible value for the top of the Y axis on 0.1 (or 0.5).

**Comment by floreks** [comment]
> I think the Y axis minimum must be fixed on 0 and the lowest possible value for the top of the Y axis on 0.1 (or 0.5).

It is fixed on 0 by default. This is just how `ngx-charts` library handles displaying graph when all y values are set to 0. Instead of displaying an empty graph it displays this. There is really nothing we can do about that.

I am also not sure about rounding values up to `0.01` as the minimal value. It would make this kind of graph appear even more often.
![image](https://user-images.githubusercontent.com/2285385/76521952-0a45a680-6466-11ea-8782-7fe5ff9ad501.png)

Generally, graphs are here to show usage changes over time and they are autoscaled to the closest minimum value. I'll slightly update it, but this under 0 value would have to be fixed on `ngx-charts` side.

**Comment by floreks** [comment]
https://github.com/kubernetes/dashboard/pull/5000 should fix both issues.
