### ISSUE TITLE
Process 302 server redirect

### ISSUE THREAD

**Issue by NikPaushkin** [kubernetes/dashboard#5065]
##### What would you like to be added
On a client, process http server `302` redirect without trying to make `XMLHttpRequest` with the url received.

##### Why is this needed
If you use a reverse proxy and user is unauthorized, that's much better to send user to your sign-in page instead of showing unclear text errors.

**Comment by floreks** [comment]
How is that related to Dashboard?

**Comment by NikPaushkin** [comment]
@floreks Right now I got this error on dashboard's front-end:
`Access to XMLHttpRequest at ..... 
(redirected from 'http://localhost:49011/api/v1/namespace') from origin 'http://localhost:49011' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Could front-end catch 302 redirect from reverse proxy and redirect user to provided url?

**Comment by floreks** [comment]
Reverse proxy in front of Dashboard should be completely independent and not rely on any logic inside the app.

Your proxy should be fully responsible for logging in, getting token and injecting it into the header. 

If proxy detects that session/token expired it should redirect user to the login page again.

As proxy is in front of application, it can fully decide what to do. There is no reason to try and force the application to do the redirect.

**Comment by NikPaushkin** [comment]
@floreks Thank you for a quick response. I agree with about all the points, but could you, please, give an example, how my proxy can decide what to do, when user has Angular SPA opened in their browse, which provides all the routing on a client side?

**Comment by floreks** [comment]
I'll check tomorrow our configuration and share as much as I can.

Basically, there is one downside when using reverse proxy.

When user is unauthorized and tries to access Dashboard, there is no issue. Proxy will redirect user to the OIDC login page and then autoredirect again to Dashboard after logging in.

When user is logged in and somehow session expires during using Dashboard, it will show error, but won't redirect to login view again unless user refreshes the page (F5).  This usually does not happen, because session lasts quite long and often expires when user is offline.

To have the best user experience we'd need to support external OIDCs ootb inside Dasbboard. This is a different feature though.

**Comment by NikPaushkin** [comment]
> When user is logged in and somehow session expires during using Dashboard, it will show error, but won't redirect to login view again unless user refreshes the page (F5). This usually does not happen, because session lasts quite long and often expires when user is offline.

That's what is my issue about. I suggested a solution with 302 processing just as a more simple for this case.

**Comment by floreks** [comment]
We can't support that and allow unknown cross origin requests/redirects. The only way to support this would be by implementing actual support for external OIDC providers in Dashboard. There is a tracking issue for that, but no one started work on this yet.

https://github.com/kubernetes/dashboard/issues/2353

/close

**Comment by NikPaushkin** [comment]
> We can't support that and allow unknown cross origin requests/redirects.

To be honest, I don't see any problem to allow redirect to a different domain (there is no secure issue). Dashboard auth UX will stay quite poor, but ok, you decide.

**Comment by floreks** [comment]
@NikPaushkin it is a major security issue if we can't control (whitelist) cross origin request/redirect domains. We would be essentially allowing phishing/cors attacks by default. I'd rather have worse UX until we support this on our side rather than a security issue that might influence all users and their sensitive data.

**Comment by NikPaushkin** [comment]
> it is a major security issue if we can't control (whitelist) cross origin request/redirect domains.

@floreks Since we're using `https` and front-end is trusting to my proxy-server, how the redirect provided by server can be unsecure or fished? We don't talk about CORS here, for any non-SPA web application 302 redirect will work like that, and there is nothing unsecure: we just need let to propogate server 302 response from SPA to browser instead of catching it like now.

**Comment by floreks** [comment]
It might be true for your configuration, but allowing redirect to any external domain gives an attacker a possibility to do a phishing attack and in certain cases might expose sensitive data to the external page. We could maybe allow redirects for the same domain to make sure that it won't redirect users outside of the "safe zone".

**Comment by NikPaushkin** [comment]
> We could maybe allow redirects across the same domain to make sure that it won't redirect users outside of the "safe zone".

@floreks Indeed. Then I could configure a redirect route on my proxy-server and send user to a needed location.
