### ISSUE TITLE
Kubernetes Dashboard freezes

### ISSUE THREAD

**Issue by Eddman** [kubernetes/dashboard#5089]
##### Environment

```
Installation method: kubeadm
Kubernetes version: 1.16.9
Dashboard version: 2.0.0
Operating system: N/A
Node.js version ('node --version' output): N/A
Go version ('go version' output): N/A
```

##### Steps to reproduce
Open Dashboard on any screen that contains charts. Leave it open/continue browsing on other tabs.

##### Observed result

After few minutes of inactivity the Dashboard page is not responding anymore. It is frozen and tab has to be closed.

##### Expected result
Dashboard will not freeze like that.

##### Comments
I guess the problem is with the new "reloading" mechanism. It does re-fetch every 5 seconds in my case.

**Comment by floreks** [comment]
It might be due to browser throttling mechanism for inactive tabs. Dashboard still works in background but does not have enough resources to properly work and short 5s refresh might cause request overlap that build up over time causing tab freeze. Right now workaround would be to increase refresh time to at least 10s for larger clusters. On small clusters with fast API responses it should not happen.

We will try to use [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) to disable periodic requests when tab is inactive and resume then once it is active again.

**Comment by mukundmckinsey** [comment]
try this one: https://grafana.com/grafana/dashboards/11802

**Comment by superbiche** [comment]
Couldn't the calls use `debounce` instead of `throttle` so the calls aren't stacked?

**Comment by floreks** [comment]
`debounce` will not work here as right now it is called by the `timer` set to a specific interval. Best solution would be to stop all timers when tab is not focused.

**Comment by VampireDX** [comment]
I met similar problem, all kubernetes-dashboard backend logs is seemed good, but the UI is freezed. The browser inspecter shows a lot of requests don't get any response.

2020/05/14 08:18:25 Getting list of all replica sets in the cluster
2020/05/14 08:18:25 [2020-05-14T08:18:25Z] Outcoming response to 10.244.0.0:20979 with 200 status code
2020/05/14 08:18:25 Getting pod metrics
2020/05/14 08:18:25 [2020-05-14T08:18:25Z] Outcoming response to 10.244.0.0:20979 with 200 status code
2020/05/14 08:18:25 [2020-05-14T08:18:25Z] Outcoming response to 10.244.0.0:20979 with 200 status code
