### ISSUE TITLE
Use another type of datastore to store data

### ISSUE THREAD

**Issue by mohamadnikan2013** [kubernetes/dashboard#5298]
##### What would you like to be added
As a user, I don't like to use a secret to store data (CSRF token or key-holder) or a configMap to store dashboard-settings so I think about other data  

##### Why is this needed
I want to run Kubernetes dashboard out-of-cluster and I don't wanna store my secrets and configMap in-cluster so I need a solution to store data out-of-cluster

##### Approaches 
Use another backend storage like `ETCD` or something else

**Comment by floreks** [comment]
This is most probably not something we'll ever add upstream. You are welcome to fork Dashboard and add such changes on your own. Dashboard is intended to run inside the cluster or at least have access to Kubernetes to use it as a storage. Kubernetes underneath already uses `etcd` to store all the data. We do not have any kind of data persistence layer on the backend side. We rely fully on Kubernetes to handle that and we want to keep it that way.  It was done on purpose to simplify the data management and fulfill stateless app requirements, so that Dashboard can be easily scaled inside the cluster.

/close

**Comment by mohamadnikan2013** [comment]
@floreks 
I understand that Kubernetes underneath already uses ETCD, but I don't think it's a good idea to use only Kubernetes as the storage to persist data and share them between pods. because users want to manage Kubernetes with dashboard and I don't think it's a good idea to see dashboard deployment and secrets and namespace in the dashboard because of this I wanted to deploy Kubernetes dashboard out-of-cluster so Kubernetes users won't aware of dashboard deployment and secrets. but I realized that Kubernetes dashboard use secrets and configMap inside cluster to store data. do you have any idea how can I deploy Kubernetes dashboard out-of-cluster without using the Kubernetes API server as storage? I want to break this dependency and deploy the Kubernetes dashboard out-of-cluster.

**Comment by floreks** [comment]
This is not possible as I have said previously. You would have to fork Dashboard and build from the scratch data persistence and management layer in the backend. We do not support that and never will officially. If you don't want users to see some resources then you should configure proper RBAC rules for them.
