### ISSUE TITLE
Make Helm Chart release more clear

### ISSUE THREAD

**Issue by pierluigilenoci** [kubernetes/dashboard#5699]
##### What would you like to be added

I would like, whenever a new version of the Helm Chart is released, it will be posted on the releases page. https://github.com/kubernetes/dashboard/releases
As does ingress-nginx, for example: https://github.com/kubernetes/ingress-nginx/releases

##### Why is this needed

To be notified whenever it happens and keep clusters up to date without having to proactively verify this repo. 

##### Comments
Please 🙏

**Comment by floreks** [comment]
The issue is that helm chart versioning and releases are basically independent of our normal releases. They are also fully automated and every change of chart automatically triggers the release of the helm chart.

From what I see new artifact hub offers an option to "star" a helm chart directly and get notifications on every release. I guess it is the easiest way to stay up-to-date.
![Zrzut ekranu z 2020-12-02 11-30-43](https://user-images.githubusercontent.com/2285385/100861242-d6962b00-3491-11eb-9ab0-5465f593b34f.png)

**Comment by floreks** [comment]
I think using helm built-in feature should be the way to go here since our app/chart releases are independent.

/close
