### ISSUE TITLE
Differences between max lenght App name

### ISSUE THREAD

**Issue by kwodzynski** [kubernetes/dashboard#576]
#### Issue details
Differences between max lenght App name in the form on the web page and in yaml/json file
##### Environment
```
Dashboard version: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.0.0
Kubernetes version: v1.3.0-alpha.0.604+b494cbc0c17dd7
Operating system: linux/amd64
Node.js version: v0.10.40
Go version: go1.4.2
```

##### Steps to reproduce
I try deploy aplication on the web page using an add form and using yaml/json file (both the web application and by commend "kubectl" in console)

##### Observed result
In the form validation approve max lenght of 24 chars for App name, but in yaml/json file I can deploy apllication, which name contains 253 chars. Additionally, if name of application contains more than 50 characters, name is hidden under a PODS/EVENTS table and button "delete" is invisible and if name's lenght is nearing maximum (253), end of the name and button "delete" shows on the right side of the table.
![tolenghtname](https://cloud.githubusercontent.com/assets/18006407/14040942/494005a6-f264-11e5-8251-e30dbb585403.png)

 
##### Expected result
I think that max lenght of App name should be the same regardless of the method of deploying application and should be limited to 24 characters.

##### Comments
Possibly may be thinking about change maximum lenght of application name

**Comment by floreks** [comment]
App name in deploy form was limited because when App is deployed service (and possibly other resources) may be created also and service name is restricted to 24 chars. We've had to limit app name to max length of resource with smallest limit.

Deploy with the file requires to directly specify resources name and this way original kubernetes limits are applied.

As for the second issue marked on the screenshot, it should be fixed. Thanks for finding that. You can also check other places for long names handling.

**Comment by cheld** [comment]
Please make sure the mobile form factor works as well

**Comment by cheld** [comment]
On logs page the name is cut without indication of dots...
