### ISSUE TITLE
External service checkbox is not validated

### ISSUE THREAD

**Issue by cheld** [kubernetes/dashboard#588]
#### Issue details
It is possible to check "Expose service externally" without selecting port.

##### Steps to reproduce
Press +
Add required fields
Leave port empty
Check "Expose service externally"

##### Observed result
No external endpoint is created. Check is simply ignored

**Comment by bryk** [comment]
Oh, yeah. This should be changed.

**Comment by cheld** [comment]
I will have a look

**Comment by digitalfishpond** [comment]
What would be ideal here? 

To grey out the check box until a port has been defined? or to have a ng-message under the checkbox or under the port on click of the Deploy button if the checkbox is checked and no port is defined? 

I personally think that 'A port must be defined to expose service externally' under the checkbox would be the best option because it _shows_ the user the condition they have requested that is causing the problem, and it _tells_ the user what to change to enable that request. The greyed out checkbox option does not directly tell the user what needs to be done to enable the checkbox, (though it's admittedly an easy guess). 

Any opposite views?

**Comment by bryk** [comment]
>  personally think that 'A port must be defined to expose service externally' under the checkbox would be the best option because it shows the user the condition they have requested that is causing the problem, and it tells the user what to change to enable that request. The greyed out checkbox option does not directly tell the user what needs to be done to enable the checkbox, (though it's admittedly an easy guess).


I like this a lot :)

**Comment by digitalfishpond** [comment]
@cheld, have you had a chance to look at this, or can I fix?

**Comment by cheld** [comment]
I started to look at it.

**Comment by digitalfishpond** [comment]
Ok :)

**Comment by cheld** [comment]
Done
