### ISSUE TITLE
No error message is shown on failed user action

### ISSUE THREAD

**Issue by cheld** [kubernetes/dashboard#592]
#### Issue details

There is no proper error handing in dashboard yet.
##### Steps to reproduce
1. Open two browsers
2. Press +
3. Enter same data twice
4. press deploy
##### Observed result

No reaction in second browser.
##### Expected result

Error pop-up or re-validation of form
##### Comments

Dashboard should have some kind of error handing. Our focus is strong validation, so the error should not occur and handling can be simple.

**Comment by cheld** [comment]
Remark: I have not tested, but I assume that any server error is not handled. Also, I assume not only this action, but any place in Dashboard does not handle errors. I think the only exception is deploy from file

**Comment by digitalfishpond** [comment]
Server errors do seem to be handled:

handleDeploy() in src/app/backend/handler/apihandler.go handles the errors and src/app/frontend/error/ contains the frontend components. 

The problem you decribe is specific to the deploy page: There is some weird behaviour when two browsers are open that I can't work out, and it's to do with one-way and two-way bindings I think. 

Scenario 1:

1. Open 2 browser windows side by side (named 'B1' and 'B2' hereon) running dashboard, 
2. Click '+' on both browsers
3. Enter an App Name and Container Image on B1
4. Click on App Name field on B2 --> The name entered on B1 appears
5. Click away from App Name Field on B2 --> validation message for empty field appears
6. Over-write App Name on B2 with  --> editing appears simultaneously on B1 and validation messages disappear
7. Click 'Deploy' on B1 --> B1 shows the newly created Replication Controller, B2 refreshes to show an empty 'Deploy' form

Scenario 2:

1. Follow step 1 from scenario 1
2. Click '+' only on B1
3. enter App Name and Container Image on B1
4. Now Click '+' on B2
5. Click and then click away on the App Name field --> the fields are NOT filled, and 'required' validation messages kick in
6. In B2, write an App Name that is different from the one in B1 --> On screen, the App Name of B1 is updated simultaneously to show the App Name being edited in B2.
7. Click Deploy in B1 --> a Replication Controller has been created with the name originally inputted in B1 rather than the one shown at the time of deployment.

Scenario 3:

1. Follow steps 1-5 of scenario 1
2. With the validation message still showing on B2 for App Name, now click and click away on Container Image field on B2 --> 2 validation messages are now showing, but both fields are completed
3. click 'Deploy' on B2 --> B1 refreshes to show an empty form, B2 shows no difference.
4. No RCs have been deployed

As I say, I don't think this is an issue of back end errors not being shown to the user, because they are handled. This is a muddled MVC binding issue.

**Comment by digitalfishpond** [comment]
TL:DR - When 2 browsers are open on the deploy page, entries from the user on one browser are reflected (after initial focus) on the view of the second browser, but this data is not relayed to the second browser's controller/model. So the user sees something that the controller/model does not see causing possible conflict at the time of deployment.

**Comment by bryk** [comment]
Can we show an error dialog for situations like this?

**Comment by digitalfishpond** [comment]
Do we want to restrict the use of more than one browser at a time? It's clearly nearly impossible to guarantee a safe deployment when the deployment page is open in 2 browsers... How would this work if 2 users were using dashboard on the same system simultaneously?

**Comment by cheld** [comment]
No, we do not want to restrict to one browser. Besides the fact that we do not want such a restriction, it wouldn't  help on any other issues like "Run as priviliged" see above. (I am sure that there are many more issues - they are just not entered)

As far as I understand, the frontend does not contain error handling that is visible to the user. Errors are just logged
https://github.com/kubernetes/dashboard/blob/master/src/app/frontend/deploy/deployfromsettings_controller.js#L227

My proposal would be to implement something like a wrapper around resource that will open the error dialog, if needed. But there might be other ways. e.g. we let the error propagate and catch at some other central place? Not sure if Angular supports central error handling. (other frameworks do)

**Comment by bryk** [comment]
> My proposal would be to implement something like a wrapper around resource that will open the error dialog, if needed. But there might be other ways. e.g. we let the error propagate and catch at some other central place? Not sure if Angular supports central error handling. (other frameworks do)

Yes, this would be perfect. To handle all errors at once.

**Comment by digitalfishpond** [comment]
so, @bryk , you're saying this is not already done? I was under the impression that this was precisely what src/app/frontend/error/* was doing?

**Comment by bryk** [comment]
AFAIK this is not done.

**Comment by digitalfishpond** [comment]
Ok :)

**Comment by maciaszczykm** [comment]
Errors like these are handled in the current version. We display the error message in a dialog, i.e.:

<img width="431" alt="Zrzut ekranu 2020-05-28 o 14 50 33" src="https://user-images.githubusercontent.com/2823399/83143681-9c1e9080-a0f2-11ea-91f7-81a2d67c992d.png">
