### ISSUE TITLE
Search shouldn't break just because a resource version doesn't exist

### ISSUE THREAD

**Issue by mikebell90** [kubernetes/dashboard#6356]
##### Environment

```
Installation method: helm chart
Kubernetes version: 1.18
Dashboard version (v1.x is not supported. Use v2.0 or later.): 2.3.1
```

##### Steps to reproduce

Search doesn't work against 2.3.1. I traced this to the switch to ingressv1.

##### Observed result

You see your search results and then a 404. The actual search seems to loop through all object types. When it hits a 404 on ingress (because v1 doesn't exist) it blows up

##### Expected result

It's absolutely fine to require the latest version of a resource and to break on that resource. It's not fine for search overall to break. The logic should be able to handle this correctly.

**Comment by floreks** [comment]
We can't consider this a bug as on every release page we provide a compatibility matrix with officially supported Kubernetes versions. Dashboard `2.3.1` officially supports Kubernetes `v1.20` and `v1.21`. Compatibility with other versions, in this case `v1.18` is not guaranteed.

/close

**Comment by mikebell90** [comment]
I think you miss the point @floreks . Namely that a single 404 shouldn't break the overall search. I totally get that you only test a couple versions. Point is this is a bad error handling design, and will bite users in other circumstances

**Comment by floreks** [comment]
We could improve the behavior here but not in a way you'd expect. Right now the only thing that is misleading is showing 404 error instead of 5XX internal server error with a message that the API version of one resource is not supported by your Kubernetes cluster version.

Our search is right now basically a filter. It makes requests to all top-level resources in parallel and then the error interceptor intercepts the error coming from one of the resource endpoints. If we'd actually switch to using a single dedicated search endpoint on the backend side, then you'd for sure get a direct error with the message that you are using some unsupported k8s version.

This behavior is consistent for all resources. If you will try to open a list of ingress resources then you'll get the same error. The original issue will always be that you are using an unsupported Kubernetes version and we can't guarantee that any part of Dashboard will work as expected by the user. Our goal is to have a consistent UI when using supported Kubernetes versions and we do not test how it behaves with unsupported versions.

**Comment by mikebell90** [comment]
That's fine, I'd argue that Search shouldn't fail at first failure - that it should try to gather what successes it has and display them. However that's your call.

**Comment by floreks** [comment]
It should fail if the error that is thrown is a critical error and in this case, the missing API version required to list a resource is a critical error. The only misleading thing here is the 404 error instead of 5XX. It incorrectly suggests that this is a minor error. If we'd fully move the search to the backend as it is usually done, then there would be no question whether this is correct behavior or not. Using a non-existing API version would simply throw an internal error. We can't just ignore such errors and go on.
