### ISSUE TITLE
The notification panel's tooltip is difficult to translate to other language.

### ISSUE THREAD

**Issue by qlijin** [kubernetes/dashboard#6620]
##### What would you like to be added
The notification panel's tooltip is difficult to translate to other language.  The i18n need static text but the text is dynamic.  It is writed by angular code to show or hide one of two sentence. 

I want to improve it. There is a method by using static html element to fix it. :)

![image](https://user-images.githubusercontent.com/515900/141059052-bef738fb-9ea3-43e4-8f4d-bddf3d26de7c.png)

The code is in https://github.com/kubernetes/dashboard/blob/15300bd43793dd12e8c38feaf4e4bee686d10905/src/app/frontend/chrome/notifications/template.html#L21

**Comment by floreks** [comment]
There are lots of places in the code where we have text that is not being translated. All those places should be checked first, listed and a single issue for all those should be created. Having an issue for such a small thing is suboptimal.

**Comment by qlijin** [comment]
This issue is not just for translating. It is to resolve a problem that some text can not be translated directly! You can check this place's code above in other language, it is alse not translated. Because it is a technical problem so that guys can not translate it.  
I raised this issue to better discuss how to solve this problem and listen to your opinions.I

**Comment by qlijin** [comment]
This issue is not just for translating. It is to resolve a problem that some text can not be translated directly! You can check this place's code above in other language, it is alse not translated. Because it is a technical problem so that guys can not translate it directly.
I raised this issue to better discuss how to solve this problem.

**Comment by floreks** [comment]
The same issue applies to a lot more places in the code. There are multiple places where we'd have to change the code in order to enable translation for some strings. That's why there should be a single issue with the list of all those places, instead of creating new issues every time someone stumbles upon such place in the code.

**Comment by qlijin** [comment]
Well, I have not seen this single issue you metioned yet.  What I want to do is just to improve this palce's code above so that pepole will be able to translate it.  This is important of that it's about the code thing firstly

**Comment by shu-mutou** [comment]
In this issue, how about focusing into translations about user actions. It's more important for user experience than items for refering, i.e. status icons, that remains un-targeted for translation, I think.
As far as I browse, un-translated parts about user actions are almost fixed in his PR.

Actually, many tooltips for refering are un-targeted for translation for now. But it's better to fix efficiently them in other issue or PR due to its amount. IMHO.
