### ISSUE TITLE
Pod logs menu is really hard to use

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#689]
![selection_072](https://cloud.githubusercontent.com/assets/1159999/14886641/1dd7e2fe-0d52-11e6-90af-2c599e359d9d.png)

It shows only top10 pods without indication that there are more and the "running since" click target is ambiguous. I dont know why it is clickable, not the name.

**Comment by cheld** [comment]
I think there is also an issue with long pod names, as far as I remember

**Comment by bryk** [comment]
@digitalfishpond Added one more thing to the complaint list

> The logs pop-up drops off the edge of the window when the name is long and it is the first time that has been clicked (subsequent clicks make the whole pop-up appear correctly):

**Comment by digitalfishpond** [comment]
A suggestion has been made to drop this menu altogether, mainly due to the issues caused by the possibility of large quantities of pods, and long pod names:

1) Large quantities of pods: While we can display/load a few pods at a time with md-virtual-repeat, you still need to transfer all pods, and then there's the issue of how the user then scrolls through 1000 pods in a tiny window

2) long pod names: [This page](https://material.google.com/components/menus.html#menus-simple-menus) recommends that if a menu contains long names that might be truncated, a dialog should be used instead. This is material spec, and should be followed.

Now the question is, do we implement a dialog instead, or do we drop this feature altogether as un-useful?

**Comment by cheld** [comment]
In general, we should optimize for the common (99%) use case. For the remaining 1% use-cases (e.g. extremely, unrealistic long names) I would not care so much. Just make sure it works somehow and is not a bug...

**Comment by digitalfishpond** [comment]
Thanks Christoph, that addresses point 2 (though I would argue that pod names over 21 characters may not be so uncommon), what about point 1?

**Comment by bryk** [comment]
@cheld  I'd still argue about the usefulness of the logs-menu-on-RC-list. You've got there a randomized list of pods with no info at all. You could just click though to the details of a RC and see the list of pods with all you need (statuses, etc). You can the click and see logs of any pod there.  You can search for a pod you like there, and do all the powerful stuff. 

So I'd still remove the pod logs menu and route users through the details page.

What do you think?

cc @romlein

**Comment by maciaszczykm** [comment]
I agree with @bryk, IMO there is no need for this menu anymore.

**Comment by cheld** [comment]
yes fine with me

**Comment by digitalfishpond** [comment]
Ok, I will remove it now.
