### ISSUE TITLE
🐛 Helm chart repo down

### ISSUE THREAD

**Issue by gvillafanetapia** [kubernetes/dashboard#7048]
### What happened?

https://kubernetes.github.io/dashboard/ is throwing 404 not found so I can't add helm repo following the instructions of https://artifacthub.io/packages/helm/k8s-dashboard/kubernetes-dashboard

### What did you expect to happen?

https://kubernetes.github.io/dashboard/ should return an index page to helm charts and helm repo added

### How can we reproduce it (as minimally and precisely as possible)?

Navigate to https://kubernetes.github.io/dashboard/

### Kubernetes Dashboard version

any

### Kubernetes version

any

**Comment by floreks** [comment]
Works as expected to me
![image](https://user-images.githubusercontent.com/2285385/165747875-072177b5-dea6-4d1f-bec2-ea3d1a935a19.png)

You shouldn't actually try and open this page in the browser since it does not contain a standard `index.html` file. There is nothing to see there. It has helm-related files only.

/close

**Comment by floreks** [comment]
That's not something we have control over. It must have been either a networking issue on your side, your ISP, or a partial outage on GitHub side.

**Comment by jovyllebermudez** [comment]
yeah might be it, but it is also weird that I can access this repo and also other github.io sites, but the kubernetes.github.io I can't.
