### ISSUE TITLE
Deploying recommended setup causes removal of existing secrets

### ISSUE THREAD

**Issue by XANi** [kubernetes/dashboard#7153]
### What happened?

cert (its cert+key single file) exists just fine as secret
```
# kubectl describe secret kubernetes-dashboard-certs -n kubernetes-dashboard 
Name:         kubernetes-dashboard-certs
Namespace:    kubernetes-dashboard
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
tls.crt:  5176 bytes
```
then new version of kubernetes-dashboard is loaded:
```
# kubectl apply -f recommended.yaml
namespace/kubernetes-dashboard unchanged
serviceaccount/kubernetes-dashboard unchanged
service/kubernetes-dashboard unchanged
secret/kubernetes-dashboard-certs configured
secret/kubernetes-dashboard-csrf configured
secret/kubernetes-dashboard-key-holder unchanged
configmap/kubernetes-dashboard-settings unchanged
role.rbac.authorization.k8s.io/kubernetes-dashboard unchanged
clusterrole.rbac.authorization.k8s.io/kubernetes-dashboard unchanged
rolebinding.rbac.authorization.k8s.io/kubernetes-dashboard unchanged
clusterrolebinding.rbac.authorization.k8s.io/kubernetes-dashboard unchanged
deployment.apps/kubernetes-dashboard unchanged
service/dashboard-metrics-scraper unchanged
deployment.apps/dashboard-metrics-scraper unchanged
```
the recommended.yaml is just recommended config for 2.6 with --tls-* options added

```
# kubectl describe secret kubernetes-dashboard-certs -n kubernetes-dashboard 
Name:         kubernetes-dashboard-certs
Namespace:    kubernetes-dashboard
Labels:       k8s-app=kubernetes-dashboard
Annotations:  <none>

Type:  Opaque

Data
====
```
and the previous cert is yeeted out of existence.

### What did you expect to happen?

The existing cert not being destroyed during upgrade.

The current system of providing certs is really pretty stupid:

* `opaque` type is used instead of `tls` as it was supposed to
* manifest just creates empty secret and doesn't use it for anything by default
* automatic cert creation... doesn't save it anywhere so restart via say `kubectl rollout restart -n kubernetes-dashboard deployment kubernetes-dashboard` means the self-signed cert is regenerated and it needs to be confirmed in browser again

Hope I'm not going too much into XY problem here but cert  secret should really be:

* not existent in manifest
* loaded via kube API on start (so the secret doesn't need to exist at moment of pod start)
* if not existing created with self-signed cert and saved
* re-generated if it *was* generated and is expiring.

That way users using self-signed one (test clusters etc) could "just use it" without having to re-confirm certs and ones that configured it properly wouldn't have to script re-adding cert every time they upgrade dashboard.

### How can we reproduce it (as minimally and precisely as possible)?

Add server cert as per instructions (recommended.yaml + adding the required --tls* options) in docs then redeploy dashboard as per instructions in docs. The cert secret will be recreated, empty

### Kubernetes Dashboard version

2.6.0, 2.5.1

### Kubernetes version

1.23,1.24

**Comment by XANi** [comment]
Also the fact https://github.com/kubernetes/dashboard/issues/4444 doesn't allow to even *see* the secrets (I understand not allowing edit but blocking viewing them is a bit pointless) makes debugging that a bit annoying...

**Comment by floreks** [comment]
> The current system of providing certs is really pretty stupid:
>
> - opaque type is used instead of tls as it was supposed to

Since the secret is empty then the type does not matter at all. Users should use the tls secret with custom certificates if needed.

> - manifest just creates empty secret and doesn't use it for anything by default

True, but the users should not care that much about additional resources we use for storing config, etc. This is just an implementation detail.

> - automatic cert creation... doesn't save it anywhere so restart via say kubectl rollout restart -n kubernetes-dashboard deployment kubernetes-dashboard means the self-signed cert is regenerated and it needs to be confirmed in browser again

This is intentional as we do not want to store autogenerated certificates anywhere. They are only stored in memory. Most of the time certificates are mounted as read-only and users should not really allow any application to override the secret content. It would not be secure at all.

> Hope I'm not going too much into XY problem here but cert secret should really be:
>
> -not existent in manifest

Not really as it would complicate the whole process of providing custom certificates for the user. Right now the certificate is created as empty because the Kubernetes Dashboard `Deployment` part of the yaml contains configuration that uses this certificate and mounts it under default path inside the container. Removing that would complicate things for some users even more as they would struggle to configure everything correctly.

> - loaded via kube API on start (so the secret doesn't need to exist at moment of pod start)

Loading certificates from the API is not something anyone should ever do. Certificates used to serve the web server should be  read from the local file tree inside the application container. Ideally they should also have restricted access rights so that they couldn't be modified, only read by the application.

> - if not existing created with self-signed cert and saved

As explained previously. We do not really want to do that.

> - re-generated if it was generated and is expiring.

Autogenerated certs are valid for 1 year. This should not be an issue as they should only be used inside dev environments and are regenerated after restart.
