### ISSUE TITLE
Cypress tests to use Cucumber so more people can support

### ISSUE THREAD

**Issue by eddiejaoude** [kubernetes/dashboard#7205]
### What would you like to be added?

I am keen to add Cucumber to the Cypress testing, this will give an extra layer of abstraction.

Current
```js
   it('cluster', () => {
      NavbarPage.clickItem(NavbarPage.clusterItemId);
      NavbarPage.assertUrlContains('cluster');
    });
```

To
```gherkin
Scenario: Navigating to the cluster page
    Given I open "home" page
    When I click "#nav-cluster"
    Then I see "cluster" in the url
```

*note: more abstraction can be done with `#nav-cluster` etc, just an example*

### Why is this needed?

This will result in more people contributing to the tests and therefore improve the code coverage.

Q. I have started moving over a few examples, I can create a `draft` PR if useful?

**Comment by floreks** [comment]
Hey, we have a soft code freeze currently until https://github.com/kubernetes/dashboard/pull/7047 gets merged. Since this is a huge codebase refactoring we are not introducing any changes to the current codebase. Only important security fixes, docs changes are acceptable.

Regarding the cucumber usage, I am not super convinced it is something we really need and if it will be helpful in the long run. In general, there is no way to cover most of the cases in a generic way, and in the end, writing a new e2e test will require cypress knowledge anyway. Cypress itself already offers some really nice ways of simplifying the test flow.

Another thing is that it adds another layer of abstraction and requires us to dive into the new testing tool (besides cypress). Since there are very few active contributors (mostly me and @maciaszczykm for the new features and core project) I don't think we need to add more tools to maintain to our list.

> This will result in more people contributing to the tests and therefore improve the code coverage.

I think our main goal should be to try and get contributors for the core part of the project, not just e2e tests. I am genuinely concerned about the potential quality of such PRs. Right now it requires a bit more technical knowledge to run everything and work with the e2e, but IMHO it is a good thing.

@maciaszczykm WDYT?

**Comment by eddiejaoude** [comment]
> Hey, we have a soft code freeze currently until #7047 gets merged. Since this is a huge codebase refactoring we are not introducing any changes to the current codebase. Only important security fixes, docs changes are acceptable.

Sure 👍 

> Regarding the cucumber usage, I am not super convinced it is something we really need and if it will be helpful in the long run. In general, there is no way to cover most of the cases in a generic way, and in the end, writing a new e2e test will require cypress knowledge anyway. Cypress itself already offers some really nice ways of simplifying the test flow.

From my experience, most tests are repeatable, for example they are "click" or "assert" some text on the page, using Cucumber definitely lowers the barrier to entry

> Another thing is that it adds another layer of abstraction and requires us to dive into the new testing tool (besides cypress). Since there are very few active contributors (mostly me and @maciaszczykm for the new features and core project) I don't think we need to add more tools to maintain to our list.

There is not much more to learn, the abstraction is lightweight, it is still Cypress underneath. I am happy to give a demo if that helps?

> I think our main goal should be to try and get contributors for the core part of the project, not just e2e tests. I am genuinely concerned about the potential quality of such PRs. 

But isn't that already happening as the tests seem neglected at the moment. My first idea was to convert the existing tests, then add more around the "happy" and "boundary" conditions for the existing functionality and features. I find this is a great way to get more love and attention for the project as a whole - once people get more comfortable with the project they can contribute to the "core" part of the project too.

> Right now it requires a bit more technical knowledge to run everything and work with the e2e, but IMHO it is a good thing.

You mention that there are only 2 of you maintaining the project, would this not help in increasing that number someday? This comment could be mistaken for "gatekeeping".

At the end of the day, you are the maintainers and I am happy to go along with your decision. My goal was to try and achieve 2 things:
- improve the quality and confidence of the project by improving the code coverage
- get more community members involved and contribute to the project. This may start with tests but will lead to more core features as the awareness and their confidence grows

**Comment by floreks** [comment]
> From my experience, most tests are repeatable, for example they are "click" some text on the page, using Cucumber definitely lowers the barrier to entry

Personally, I am not a big fan of tests that only "click" and "assert" the text as they do not test the features or stories but are often written to simply boost the coverage and make the %% better. It then makes the frontend changes quite painful as even the smallest text change might simply break the tests. I'd rather have more complex test stories that cover our features and work more with the API responses rather than plain frontend text.

PS. Our current "tests" are not a good example of how I think tests should be written. It was just something to start with and they should be rewritten eventually (introduced by the external contributor and abandoned afterward 🙂). 

> There is not much more to learn, the abstraction is lightweight, it is still Cypress underneath. I am happy to give a demo if that helps?

> But isn't that already happening as the tests seem neglected at the moment. My first idea was to convert the existing tests, then add more around the "happy" and "boundary" conditions for the existing functionality and features. I find this is a great way to get more love and attention for the project as a whole - once people get more comfortable with the project they can contribute to the "core" part of the project too.

It's not that much about learning as it is about maintaining it afterward. Unfortunately from my experience contributors often lose interest quite fast after just a few contributions and we either have to keep maintaining their work or get rid of it (meaning new tools/frameworks/etc.). In the end, the core maintainers have to work with it most of the time.

I am concerned about trying to attract people by using some specific e2e "tool" since this is mostly about personal preference. Dashboard does not have a low entry point as it requires at least some Kubernetes knowledge as an addition to the Dashboard itself. Having a deeper knowledge about the core project itself first would help in boosting the potential PR quality.

> You mention that there are only 2 of you maintaining the project, would this not help in increasing that number someday? This comment could be mistaken for "gatekeeping".

It's not about trying to keep people away. We'd love to get more contributors. Unfortunately, we have to also think about the project in general. Adding more tools increases the entry point for the project as well as the overall complexity and effort to maintain everything. 

Another thing is that we have very little free time for reviews and when we do, it would be best to work with PRs that could potentially be merged quite fast (after 2-3 iterations at most), otherwise, they might get stuck in the loop for a long time and not get merged at all or the person contributing will feel discouraged and abandon it. 

Right now our goal is to completely separate the frontend and backend, then start to migrate the backend to a microservices architecture, use a gateway API and adapt the frontend to use GraphQL for data synchronization. Since it will have a great impact on the whole project, the existing e2e will anyway have to be rewritten. 

> At the end of the day, you are the maintainers and I am happy to go along with your decision. My goal was to try and achieve 2 things:
>
> improve the quality and confidence of the project by improving the code coverage

Sure, that might be a "selling point" for some people, but we can achieve that with any testing tool 🙂 

> get more community members involved and contribute to the project. This may start with tests but will lead to more core features as the awareness and their confidence grows

I guess that could work for some people. 

I wouldn't completely reject this idea for now and try to revisit it after we are finished with the migration. We hope that the architecture and tech stack changes will attract more people in the future.

**Comment by floreks** [comment]
> It would be great to have the e2e tests complete before the migration, so that when the separate and migration has happened, we still know it works as it did before

The thing is that we do not know for sure if the frontend will not have to undergo some bigger changes in order to make it work with a completely redesigned API. Those changes have a high risk of breaking the e2e tests. Since we work with our custom API, we have the ability to make breaking changes at any time and adjust everything as needed. I wouldn't want to waste time creating the e2e that could very quickly become invalid due to migration changes.

> Do you have an estimate date for the migration to complete? I still think it would be beneficial to have a good set of tests before the migrations, that can also be used during and after the migrations, being e2e tests they should work the same as before

Unfortunately, no. We do not have much time recently to work on Dashboard. Most of the time it is just 1 day a week and we also try to do some reviews and other maintenance work during this time. That's the main reason why I am concerned about adding anything new to our plate. Our schedule is more than full right now 🙂

**Comment by maciaszczykm** [comment]
See: https://github.com/kubernetes/dashboard/pull/7206
