### ISSUE TITLE
Incorrect namespace mentioned in readme.md

### ISSUE THREAD

**Issue by arc113** [kubernetes/dashboard#7216]
### What happened?

In the file at
https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md
the namespace mentioned is kubernetes-dasboard, while it should be kube-system.

If I use the namespace of the dashboard, i.e. kubernetes-dasboard in my case, then I don't get access to the resources. It must be created in kube-system namespace. I tested this on Kubernetes 1.24

Plus, I could not run the command `kubectl create` until I finally realized that its only supported on kubernetes 1.24, then I updated my client kubectl and it worked. If possible, we could mention the minimum kubernetes version required. Otherwise, I might assume that the documentation is always for latest version.

### What did you expect to happen?

Able to access all resources in kubernetes dashboard.

### How can we reproduce it (as minimally and precisely as possible)?

Visit https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md
and create the service account & the rbac in a running kubernetes-dashboard. Then try to access kubernetes dashboard, it wont show the resource list. It's like an anon user.

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge, Firefox, Others

### Kubernetes Dashboard version

v2.2.0+0.g0a30039e0

### Kubernetes version

1.24

**Comment by floreks** [comment]
Dashboard **should not** be installed in the `kube-system` namespace. It is recommended to install it in a separate namespace. `kubernetes-dashboard` namespace is the correct one here. 

Privileges are based on the `ClusterRole`, a cluster-wide resource (non-namespaced). It does not matter if you create a `ServiceAccount` in namespace `x`, `y`, or `z`. The binding in the end "grants" the privileges to the `ServiceAccount`.

> Plus, I could not run the command kubectl create until I finally realized that its only supported on kubernetes 1.24, then I updated my client kubectl and it worked. If possible, we could mention the minimum kubernetes version required. Otherwise, I might assume that the documentation is always for latest version.

Our goal is to keep the documentation in sync with the latest Kubernetes version supported by Dashboard. You can always find the newest release and the compatibility matrix on the releases list (currently [v2.6.0](https://github.com/kubernetes/dashboard/releases/tag/v2.6.0)). Since we support `v1.24`, then the `kubectl create token` command is the one you can find in our documentation.

We also do not support any combinations outside of our official compatibility matrix.

**Comment by floreks** [comment]
Since this issue is not valid plus it mentions unsupported K8S Dashboard version `v2.2.0` I am closing this one.

/close
