### ISSUE TITLE
Migrate PSP to v1 in helm chart

### ISSUE THREAD

**Issue by shu-mutou** [kubernetes/dashboard#7608]
### What would you like to be added?

dashboard already uses `policy/v1`, but helm chart uses `policy/v1beta1`.

### Why is this needed?

`policy/v1beta1` was deprecated in k8s v1.25.

**Comment by shu-mutou** [comment]
`policy/v1beta1` in `charts/helm-chart/kubernetes-dashboard/templates/psp.yaml` should be bumped to `v1`.

**Comment by jmhbnz** [comment]
Hey @shu-mutou - Should we be migrating to the new Pod Security Admission controller as part of this issue? https://kubernetes.io/docs/tasks/configure-pod-container/migrate-from-psp


Refer: https://kubernetes.io/docs/concepts/security/pod-security-policy/

> PodSecurityPolicy was [deprecated](https://kubernetes.io/blog/2021/04/08/kubernetes-1-21-release-announcement/#podsecuritypolicy-deprecation) in Kubernetes v1.21, and removed from Kubernetes in v1.25.

**Comment by sftim** [comment]
We should move to Pod Security Admission. PodSecurityPolicy v1 isn't a thing.

**Comment by jmhbnz** [comment]
I've had a look at this, migrating to pod security admission in a helm chart is not as straightforward as we thought as pod security admission is not fully supported in helm because it involves labeling the release namespace which helm does not support. Refer https://github.com/helm/helm/issues/3503. 

I've raised a draft pull request to generate some discussion on next steps.
