### ISSUE TITLE
Latest charts have not been published

### ISSUE THREAD

**Issue by llamahunter** [kubernetes/dashboard#7657]
### What happened?

The latest chart version is 6.0.5, but the latest published is 6.0.0

### What did you expect to happen?

latest chart version was published

### How can we reproduce it (as minimally and precisely as possible)?

Try to use chart version 6.0.5

### Kubernetes Dashboard version

6.0.5

### Kubernetes version

1.22

**Comment by asherf** [comment]
https://github.com/kubernetes/dashboard/actions/runs/4341100795/jobs/7580295747

**Comment by llamahunter** [comment]
> https://github.com/kubernetes/dashboard/actions/runs/4341100795/jobs/7580295747

When I go here: https://kubernetes.github.io/dashboard/index.yaml, the latest version I see is 6.0.0.

**Comment by asherf** [comment]
> > https://github.com/kubernetes/dashboard/actions/runs/4341100795/jobs/7580295747
> 
> 
> 
> When I go here: https://kubernetes.github.io/dashboard/index.yaml, the latest version I see is 6.0.0.

Yup.. something is broken with the workflow

**Comment by floreks** [comment]
ehh... that's this annoying branch auto-protection enforced by the organization on all branches. Due to this, I have to manually remove protection after every helm release and delete the branch.

The latest release should be up soon. Thanks for the report.

https://github.com/kubernetes/dashboard/pull/7660

**Comment by floreks** [comment]
PR is merged

/close

**Comment by asherf** [comment]
thank you!
