### ISSUE TITLE
can dashboard support to monitor the other cluster by login with different config file.

### ISSUE THREAD

**Issue by gudipudipradeep** [kubernetes/dashboard#7667]
### What would you like to be added?

I like setup the docker container in my laptop and planning to connect the aks cluster by giving the input of that cluster config file to see the live metrics whenever we need.

portable and whenever we can want can pass config file of cluster to see the metrics of that cluster.

### Why is this needed?

portable and whenever we we want we can pass config file of cluster to see the metrics of that cluster.

**Comment by floreks** [comment]
https://github.com/kubernetes/dashboard/blob/master/docs/common/dashboard-arguments.md

`--kubeconfig` argument can be used to access any cluster. Enabling metrics would be more tricky since it would require port forwarding metrics scraper to the same network Dashboard is running in and providing `--sidecar-host` argument.

**Comment by floreks** [comment]
Check out the https://github.com/kubernetes/dashboard/blob/master/docs/common/dashboard-arguments.md

You can provide custom kubeconfig file for auth and apiserver host for access.

/close
