### ISSUE TITLE
No rule to make target 'docker-build-head'

### ISSUE THREAD

**Issue by justas200** [kubernetes/dashboard#7681]
### What happened?

I want to build a docker image of the latest kubernetes dashboard source. In the docs it says to run the command `make docker-build-head` however such make target does not exist.

### What did you expect to happen?

To build a local docker image of kubernetes dashboard.

### How can we reproduce it (as minimally and precisely as possible)?

Run `make` command and verify suck make target does not exist in the given options.

### Kubernetes Dashboard version

master branch

### Kubernetes version

1.25

**Comment by floreks** [comment]
Docs are quite outdated right now after architecture changes and we will be updating them before the release. We no longer provide direct make targets to build a single image since Dashboard requires a multi-image setup right now. If you take a look at root `Makefile` it will show you all top-level targets we have. `make run` will build all images and run prod version of the app locally using `docker compose`.
