### ISSUE TITLE
Is kubernetes-dashboard v2.7.0 compatible with AKS 1.26.6

### ISSUE THREAD

**Issue by sunpm6** [kubernetes/dashboard#8210]
### What would you like to be added?

Is kubernetes-dashboard v2.7.0 compatible with AKS 1.26.6

I Do not see the k8s version 1.26 compatibility in here https://github.com/kubernetes/dashboard/releases/tag/v2.7.0 

### Why is this needed?

We are planning to upgrade our cluster to 1.26.6 and planning to use kuberntes-dashboard v2.7.0. So need confirmation on this.

**Comment by CWoodall2100** [comment]
We are also looking for an answer to this. Working on compatibility for K8s 1.26 and 1.27 clusters.

**Comment by floreks** [comment]
The compatibility matrix is always provided on the release page: https://github.com/kubernetes/dashboard/releases/tag/v2.7.0

We cannot guarantee full compatibility. This basically means that there is a high chance Dashboard will be fully functional with the newer version of Kubernetes, but in case some resources would not be able to work due to API version changes we will not be providing any fixes for that.

/close

**Comment by shazib-summar** [comment]
@floreks none of the versions in the releases page depict compatibility for 1.26. It seems as if 1.26 was skipped altogether
