### ISSUE TITLE
Suggestion for korean translation of "Horizontal Pod AutoScaler"

### ISSUE THREAD

**Issue by FacerAin** [kubernetes/dashboard#8512]
### What would you like to be added?

@seokho-son
Thank you so much for carrying out the wonderful Korean translation project! I have a suggestion regarding the translation.

The current translation for **“horizontal pod autoscaler”** is **“호레잔틀 파드 오토스케일러”**. 

https://github.com/kubernetes/dashboard/blob/fdc83e5623f44fe52c5c94d245fd490a0b94a60d/modules/web/i18n/ko/messages.ko.xlf#L1573

However, “호레잔틀” is not a commonly used translation and could potentially confuse users. 

Therefore, I suggest that we consider using **“수평 파드 오토스케일러”** or retain the **original term** as per the link below.

It also seems necessary to work the following words.
https://github.com/kubernetes/dashboard/blob/fdc83e5623f44fe52c5c94d245fd490a0b94a60d/modules/web/i18n/ko/messages.ko.xlf#L1379

If possible, I would like to contribute to this part! Thank you.

Reference Link
- https://kubernetes.io/ko/docs/tasks/run-application/horizontal-pod-autoscale/

### Why is this needed?

Readability for korean users.

**Comment by seokho-son** [comment]
Hi @FacerAin 
Thank you for your interest and suggestion!
Firstly, as a Korean reviewer, I agree that "호레잔틀" feels like an awkward expression. 

For the K8s Docs Website, we follow the principles of the Korean localization team in translating terms. However, for the Dashboard localization, we aimed to maintain consistency and use expressions that are more familiar to users. That's why we included "호레잔틀," which is a phonetic representation.

With the term "Horizontal," people in Korea tend to pronounce it differently (in case of me, "호리즌탈"), making its Korean translation somewhat tricky. However, leaving "Horizontal Pod Autoscaler" solely in English doesn't seem ideal for consistency either.

What do you think about using "Horizontal 파드 오토스케일러" instead?

**Comment by FacerAin** [comment]
@seokho-son 
Thank you for a review. 
As you mentioned, **"Horizontal 파드 오토스케일러"** seems to be a suitable alternative in terms of consistency and semantics.
I will request a PR reflecting the suggestions. 
Thank you again! ☺️☺️
