### ISSUE TITLE
New Release with support for Kubernetes v1.28

### ISSUE THREAD

**Issue by Starbix** [kubernetes/dashboard#8568]
### What would you like to be added?

A new official release with support for Kubernetes 1.28 (and possibly 1.29) would be great.
Is there a plan to go out of alpha for v3?

### Why is this needed?

We use Kubernetes Dashboard extensively in our clusters and we are in the progress of updating them all to 1.28.

**Comment by darmbrust** [comment]
Is the current alpha version known to be broken on 1.28?  I've tried installing dashboard on EKS hosted 1.28 a couple of different ways, and each was has failed.  One way seems to result in an error saying you need to install CRDs, another fails because it can't reach the API address - not sure if my EKS cluster has something wrong, or if there is a specific way a cluster has to be configured to allow worker nodes to talk to the 172.x.x.x control plane... in my pretty basic EKS install there is no route...

**Comment by Farhanec07** [comment]
Is there any tentative date for stable release?

**Comment by maciaszczykm** [comment]
Hopefully this week. We have already started pushing new images.
