### ISSUE TITLE
difficulty getting started

### ISSUE THREAD

**Issue by dberardo-com** [kubernetes/dashboard#9002]
### What should be cleaned up or changed?

i am following the readme to get started with the platform. installation via helm works well, but then i am stuck logging in.

in previous version there was the possibility to skip login, which was just great for a quick start.

now i am getting pretty frustrated, as i am creating serviceaccounts with tokens and keep getting an unmotivated  "Unauthorized (401): Invalid credentials provided" error from the GUI.

i would suggest:

* make an easier beginner-oriented step-by-step guide to access the GUI in the simplest way
* let me know what i am doing wrong
* reinstate the skipLogin feature

### Why is this needed?

increase popularity of this tool throughout community and lower entry barrier

**Comment by mathematikoi** [comment]
i keep getting Unauthorized (401): Invalid credentials provided too with no clue what is happening!

**Comment by dberardo-com** [comment]
i believe my problem was some sort of cookies in the browser, which was perhaps set from previous attempts or previous versions of the dashboard.

**Comment by floreks** [comment]
If you're doing a major upgrade then you should always clean up the cookies or use incognito mode. Our docs contain up-to-date information on how to [install](https://github.com/kubernetes/dashboard?tab=readme-ov-file#installation), [open](https://github.com/kubernetes/dashboard/blob/master/docs/user/accessing-dashboard/README.md), and [access Dashboard](https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/README.md) with information on how to [create an example user](https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md). If you are doing a clean install and using incognito mode then I don't see how it could not work.

As for the skip login feature, we will not be bringing it back since the API no longer supports acting on behalf of itself. It is mandatory to provide credentials that API can use to authenticate and authorize all actions. The code that was allowing API to use its' own permissions has been removed. It was done mostly for security reasons but also to simplify overall architecture and multi-container setup.

/close
