### ISSUE TITLE
Service status icon

### ISSUE THREAD

**Issue by edouardKaiser** [kubernetes/dashboard#920]
#### Issue details

For certain services, I have the "waiting for something" icon as a status next to the name, but I have no idea what it means:

![image](https://cloud.githubusercontent.com/assets/7731641/16176888/0ccbed1c-365f-11e6-9f4b-544dddf838f1.png)

Is it normal ? Should we display a label when mouse is over ?

##### Environment
```
Dashboard version: 1.1.beta3
Kubernetes version: 1.2.4
```

**Comment by floreks** [comment]
There should be a tooltip that says 'Service is in pending state.' This basically means that depending on service type, Cluster IP or external endpoint is not yet assigned. Tooltip is not displayed because of a bug. We'll fix that.

@digitalfishpond could you take a look as you were doing this. Not existing localization is used in html template.

**Comment by bryk** [comment]
@digitalfishpond Can you add a tooltip to the services status icon? With @floreks' explanation :)

**Comment by digitalfishpond** [comment]
Done
