### ISSUE TITLE
求救, 登陆进去后什么都看不到

### ISSUE THREAD

**Issue by luyanfeng** [kubernetes/dashboard#9534]
求救, 登陆进去后什么都看不到,
我是这么安装的:

```shell
// Add kubernetes-dashboard repository
helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/

// 安装部署 Deploy a Helm Release named "kubernetes-dashboard" using the kubernetes-dashboard chart
helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --create-namespace \
 --namespace kubernetes-dashboard \
 --set kong.proxy.http.enabled=true

// 启动代理
kubectl -n kubernetes-dashboard port-forward svc/kubernetes-dashboard-kong-proxy 8443:443 --address=0.0.0.0
```

### vim admin-user-dashboard.yaml: 
```shell
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: kubernetes-dashboard

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: kubernetes-dashboard
```

### 添加自定义用户, 默认用户权限不足
```shell
kubectl apply -f admin-user-dashboard.yaml
```
### 生成 用户 admin-user 的 access token
```shell
kubectl create token  admin-user  --namespace kubernetes-dashboard | tee admin-user.token

```

结果, 远程登陆进去看不到任务信息:
![图片](https://github.com/user-attachments/assets/288d1bce-a607-4e67-863e-0b32d0b38fe2)

**Comment by floreks** [comment]
Please use english to provide more details about your setup and how did you access the UI. Potentially, it could be due to exposing Dashboard using `--address=0.0.0.0` and then trying to access it over HTTP. I would have to see how you are logging in (via header or login view)?

I can also see that you are trying to use `--set kong.proxy.http.enabled=true` for some reason. It shouldn't be needed. It looks to me like protocol mismatch underneath. Logs from containers and request details from browser could provide more insight into the issue.

**Comment by gaozhikang1** [comment]
我也有同样的问题，你解决了么
