### ISSUE TITLE
Namespace selector: default to the default namespace

### ISSUE THREAD

**Issue by bryk** [kubernetes/dashboard#978]
As @bgrant0607 correctly pointed out in https://github.com/kubernetes/dashboard/issues/908#issuecomment-229380118 kubectl defaults to the detault namespace. This is different from the UI where we default to all user namespaces.

How about we change the behavior to:
1. default to the default namespace
2. allow to select to see resources from all namespaces (as opposed to current "all *user* namespaces)

One benefit is command line and UI consistency. The other is that we'll no longer have to deal with the definition of "user" namespaces.

Opinions?

@romlein @floreks @cheld

**Comment by floreks** [comment]
I agree with proposed change. It is exactly how kubectl does it. One namespace or all namespaces.

**Comment by edouardKaiser** [comment]
I understand the thought process behind this proposal, but as a user,
default is literally the less interesting namespace to see when you open
the dashboard. Because most of the people will create separate namespace
representing their organisation. So default will probably be almost empty.

**Comment by floreks** [comment]
> I understand the thought process behind this proposal, but as a user,
default is literally the less interesting namespace to see when you open
the dashboard. Because most of the people will create separate namespace
representing their organisation. So default will probably be almost empty.

The problem here is that different users may threat namespaces differently. One may create namespace per application, other one will create only namespaces like `dev` `staging` `prod`, next one will use it as namespace per organisation/user. That's why by default we'd like to show `default` namespace and allow user to pick either different one or all namespaces.

Additionally with IAM (#964) support that we'll try to provide, we may decide to show only namespaces that user has access to. Kubectl also supports [setting namespace preference](http://kubernetes.io/docs/user-guide/namespaces/). We could probably add support for that also.

**Comment by bryk** [comment]
> I understand the thought process behind this proposal, but as a user,
default is literally the less interesting namespace to see when you open
the dashboard. Because most of the people will create separate namespace
representing their organisation. So default will probably be almost empty.

What do you do for kubectl? Do you set it to your namespace? Or you always get stuff from all namespaces?

**Comment by edouardKaiser** [comment]
I specified the namespace I use the most in the context configuration.
